### ISSUE TITLE
[enterprise-3.9] Edit suggested in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by nickcmaynard** [openshift/openshift-docs#10074]
### Which section(s) is the issue in?

Pod autoscaling definition.

### What needs fixing?

The HPA definition sample is out of date.  
3.9 uses `apiVersion: autoscaling/v1` with different specification entries.

A valid example:

```yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: frontend
  targetCPUUtilizationPercentage: 80
```

The pod autoscaling document needs technical oversight and updating for 3.9 validity.
