### ISSUE TITLE
Document public logging and metrics URL configuration

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#1061]
New master config options:

```
assetConfig:
  ...
  loggingPublicURL: https://example.com/logging
  metricsPublicURL: https://example.com/metrics
```

See https://github.com/openshift/origin/pull/4954
https://trello.com/c/spGwc9de/129-2-web-console-logging-and-metrics-discovery
