### ISSUE TITLE
[enterprise-3.9] Edit suggested in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by sergioperez** [openshift/openshift-docs#10737]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html

### What needs fixing?

I've tried to create an Autoscaler object using the first definition, and I just get the error:
error: unable to recognize "create_tasksapp_autoscaler.yaml": no matches for extensions/, Kind=HorizontalPodAutoscaler

If I use oc autoscale, the created object does not use the v2 Autoscaler as specified in the docs. It creates the following object instead:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: tasks
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: tasks
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
```
