### ISSUE TITLE
Documentation for Keystone IdP

### ISSUE THREAD

**Issue by sseago** [openshift/openshift-docs#1073]
This PR adds a new Keystone Identity Provider: https://github.com/openshift/origin/pull/4951

Here's a sample config snippet: (annotations to the side in yaml comments)
```
oauthConfig:
  ...
  identityProviders:
  - challenge: true     # When true, unauthenticated token requests from non-web clients (like the CLI) are sent a WWW-Authenticate challenge header for this provider.
    login: true         # When true, unauthenticated token requests from web clients (like the web console) are redirected to a login page backed by this provider.
    name: keystone_auth # This provider name is prefixed to the returned user ID to form an identity name.
    provider:
      apiVersion: v1
      url: https://keystone.example.com:5000/v3 # Keystone auth endpoint URL
      domainName: default      # Keystone domain name. In Keystone, usernames are domain-specific. Currently this IdP only supports a single domain at a time.
      kind: KeystonePasswordIdentityProvider
      ca: ca.pem               # Optional: Certificate bundle to use to validate server certificates for the configured URL.
      certFile: keystone.pem   # Optional: Client certificate to present when making requests to the configured URL.
      keyFile: keystonekey.pem # Key for the client certificate. Required if certFile is specified.
```
Set KeystonePasswordIdentityProvider to authenticate against an OpenStack Keystone v3 server. The primary use case here is to share a common user base with an OpenStack environment in which OpenStack is configured to store users in an internal Keystone database (vs. using LDAP or another external identity source)
