### ISSUE TITLE
OCP 3.10 Release Notes Feedback

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#11165]
### Which section(s) is the issue in?
3.10 Release Notes
https://github.com/openshift/openshift-docs/pull/11010

### What needs fixing?

Comments from @dmoessne:

 Depricated/Removed/No Longer supported (ip, dns,...)
  I know customers who actually needed to use (some) of them to get OCP working, I might miss something, but are those being deprecated/removed,... without a
  successor or alternatives or new features ? If not, we should link to those alternatives, I think.

- batch/v2alpha1 API Version No Longer Served by Default
  Same as above, it is a bit unclear to me what and where the change needs to be done

**Comment by ahardin-rh** [comment]
@liggitt Can you please help me with doc updates? Thanks!

**Comment by liggitt** [comment]
this can be re-enabled in the master-config.yaml file if required:

```yaml
kubernetesMasterConfig:
  apiServerArguments:
    runtime-config:
    - batch/v2alpha1=true
    ...
  ...
...
```
