### ISSUE TITLE
Document SNI certificates

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#1143]
https://github.com/openshift/origin/pull/5097 added support for setting your own serving certificates for the public hostnames for your API and console servers.

Placeholder description from PR:

Named certificates can be specified in the master config (servingInfo and assetConfig.servingInfo) or in the node config (servingInfo). This allows setting a certificate to use for a particular hostname or wildcard. A default cert (servingInfo.{certFile,keyFile}) is still required in addition to namedCertificates

Note: Currently, this should only be used to set certificates for the `publicMasterURL` host. Serving a different certificate to the internal `masterURL` host will result in TLS errors in infrastructure components attempting to contact the master API on the internal `masterURL` host.

Example master config:
```
servingInfo:
  ...
  namedCertificates:
  - certFile: custom.crt
    keyFile: custom.key
    names:
    - "customhost.com"
    - "api.customhost.com"
    - "console.customhost.com"
  - certFile: wildcard.crt
    keyFile: wildcard.key
    names:
    - "*.wildcardhost.com"
  ...
```
