### ISSUE TITLE
Object Schemas Render Incorrectly

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#11734]
In the REST API reference, the object schemas are rendering incorrectly. Top-level fields are being added as children of the first child node, instead of the parent. For instance, `Build` schema has:

```yaml
spec:
  source:
    binary:
      asFile: ""
    contextDir: ""
    dockerfile: ""
```

Whereas the documentation online has:

![screenshot from 2018-08-23 11-49-59](https://user-images.githubusercontent.com/7328370/44545716-acf2d480-a6ca-11e8-9e15-153f294c9a02.png)

This is critically wrong and would be very confusing for any consumer of this spec.

/kind bugs
