### ISSUE TITLE
[enterprise-3.7] Edit suggested in file admin_guide/managing_pods.adoc

### ISSUE THREAD

**Issue by abessifi** [openshift/openshift-docs#12021]
### Which section(s) is the issue in?

Configuring the RunOnceDuration Plug-in

### What needs fixing?

The following configuration is not supported by the OpenShift Master.
Tested on OCP 3.7. When restarting the Master process it says that `kubernetesMasterConfig.admissionConfig.pluginConfig` is not supported:

```yaml
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
      RunOnceDuration:
        configuration:
          apiVersion: v1
          kind: RunOnceDurationConfig
          activeDeadlineSecondsOverride: 3600
```

The `RunOnceDuration` plugin should be configured directly on `admissionConfig.pluginConfig`:

```yaml
admissionConfig:
  pluginConfig:
    RunOnceDuration:
      configuration:
        apiVersion: v1
        kind: RunOnceDurationConfig
        activeDeadlineSecondsOverride: 3600
```
