### ISSUE TITLE
k8s : system:serviceaccount:monitoring:ansible cannot get templates at the cluster scope\

### ISSUE THREAD

**Issue by qasmi** [openshift/openshift-docs#12636]
I use k8s ansible module with service account system:serviceaccount:monitoring:ansible, my sa has master role in namesapace monitoring, my ansible role is : 
```
- name: Create OpenShift resource
  k8s:
    host: "{{ inventory_hostname }}"
    api_key: "{{ namespace_token }}"
    verify_ssl: false
    state: present
    definition: "{{ lookup('template', openshift_template) | from_yaml }}"
```
so I get this error : 
```
The full traceback is:
  File "/tmp/ansible_Uf27O5/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 121, in perform_action
    existing = resource.get(name=name, namespace=namespace)
  File "/usr/local/lib/python2.7/dist-packages/openshift-0.7.0-py2.7.egg/openshift/dynamic/client.py", line 42, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 403, 
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cert_file": null, 
            "context": null, 
            "force": true, 
            "host": "https://openshift-clostert", 
            "key_file": null, 
            "kubeconfig": null, 
            "password": null, 
            "ssl_ca_cert": null, 
            "state": "present", 
            "username": null, 
            "verify_ssl": false
        }
    }, 
    "msg": "Failed to retrieve requested object: {\n  \"kind\": \"Status\",\n  \"apiVersion\": \"v1\",\n  \"metadata\": {},\n  \"status\": \"Failure\",\n  \"message\": \"User \\\"system:serviceaccount:hub-iot-qa-monitoring:ansible\\\" cannot get templates at the cluster scope\",\n  \"reason\": \"Forbidden\",\n  \"details\": {\n    \"name\": \"hub-iot-monitoring-data\",\n    \"kind\": \"templates\"\n  },\n  \"code\": 403\n}\n", 
    "reason": "Forbidden", 
    "status": 403
}

```
Any help please ?
