### ISSUE TITLE
Wrong indent for hostPath.name

### ISSUE THREAD

**Issue by hongkailiu** [openshift/openshift-docs#12730]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/configuring_local.html#local-volume-prepare-block-devices-deploy-provisioner

### What needs fixing?
```
...
  volumes:
    - hostPath:
        path: /dev
        name: dev
```

Should be

```
...
  volumes:
    - hostPath:
        path: /dev
      name: dev
```
