### ISSUE TITLE
migration procedure from redhat/openshift-ovs-subnet to redhat/openshift-ovs-networkpolicy 3.10/3.11

### ISSUE THREAD

**Issue by megian** [openshift/openshift-docs#13134]
The migration procedure from redhat/openshift-ovs-subnet to redhat/openshift-ovs-networkpolicy is not working as described in the documentation.

### Which section(s) is the issue in?

https://docs.okd.io/3.11/install_config/configuring_sdn.html#migrating-between-sdn-plugins

### What needs fixing?

Before step one:

To change the network policy in the node group config map. Otherwise the sync pod does reset the configuration to the old network plugin, changed manually in step 1.

Manually for each node group config configmap:
oc edit configmap node-config-compute -n openshift-{master,node,infra}

```
data:
  node-config.yaml: |
    networkConfig:
      networkPluginName: redhat/openshift-ovs-networkpolicy
```

Step 3 makes absolutely no sense. This would force the cluster to be down and step 4 can not be executed, because the master API and kubelet is not up.
