### ISSUE TITLE
Link to outdated xpaas content

### ISSUE THREAD

**Issue by ncbaratta** [openshift/openshift-docs#13527]
### Which section(s) is the issue in?

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/using_images/xpaas-middleware-images#using-images-xpaas-images-index 

### What needs fixing?

The docs linked in this section are not maintained and are written for OCP 3.6 or earlier. A link to this page should not be in the 3.7+ guides.

**Comment by sheriff-rh** [comment]
@vikram-redhat  I removed the xPaaS release notes lines, is that correct? 

[Commit located here](https://github.com/openshift/openshift-docs/commit/1140f8ad3d6d339b5e1f265ec66fea96338d4ece)

**Comment by ncbaratta** [comment]
I'm not sure if that's going to fix the page in question - maybe @vikram-redhat does.

**Comment by jboxman** [comment]
@sheriff-rh @vikram-redhat 

It's my understanding (Vikram please correct me if I'm wrong) that, for each affected branch, you would need to modify the `_topic_map.yml` and remove the entry at line 1063:

```
- Name: xPaaS Middleware Images
  Dir: xpaas_images
  Distros: openshift-online,openshift-enterprise,openshift-dedicated
  Topics:
  - Name: Overview
    File: index
```

and then build locally to ensure the change is valid. I'd probably delete the `using_images/xpaas_images` directory and its contents as well.

If our `_topic_map.yml` varies between branches, cherry picking could be a challenge.
