### ISSUE TITLE
[enterprise-4.0] CRD and CR questions

### ISSUE THREAD

**Issue by barleyer** [openshift/openshift-docs#13794]
### Which section(s) is the issue in?
ALL IDPs

### What needs fixing?
https://docs.openshift.com/container-platform/4.0/authentication/identity_providers/configuring-gitlab-identity-provider.html#identity-provider-gitlab-CRD-configuring-gitlab-identity-provider
Like above section，you say: 'The following Custom Resource Definition (CRD) shows the parameters and acceptable values for a GitLab identity provider.'
```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: gitlabidp 
    challenge: false 
    login: true 
    mappingMethod: claim 
    type: GitLab
    gitlab:
      clientID: {...} 
      clientSecret: 
        name: gitlab-secret
      url: https://gitlab.com 
      ca: ... 
```
I think we better not call this like **CRD**, CRD is used for creating  a new RESTful resource path for each version you specify,maybe **CR** is more suitable for this file.Please confirm that with devs.
