### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/oab_broker_configuration.adoc

### ISSUE THREAD

**Issue by abessifi** [openshift/openshift-docs#14013]
### Which section(s) is the issue in?

- OpenShift Configuration
- Secrets Configuration

Issue: https://github.com/openshift/ansible-service-broker/issues/1188
OCP documentation to update: v3.7, v3.9, v3.10, v3.11

### What needs fixing?

**OpenShift Configuration section**

Add the following line to the table:

Field | Description | Required
-- | -- | --
namespace | OpenShift namespace where ASB is installed | N

**Secrets Configuration section**

Add the following note:

Make sure to set the `namespace` parameter to the ASB project's name so the broker can fetch the secrets.

```yaml
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  image_pull_policy: "IfNotPresent"
  sandbox_role: "edit"
  keep_namespace: false
  keep_namespace_on_error: true
  namespace: <PUT NAMESPACE OF BROKER HERE>
```

If the `namespace` parameter is omitted, you'll see the following warning log message:

```
[2019-03-06T16:24:32.778Z] [WARNING] - Unable to load secret 'aws-access-secret' from namespace ''
```
