### ISSUE TITLE
group sync needs to indicate that userNameAttributes needs to match LDAP configuration

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#1424]
In the base LDAP configuration for OpenShift you have something like:

``` YAML
...
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
```

And then in the group sync command, there is an element called userNameAttributes.

The example LDAP configuration in the documentation uses "uid" as the preferredUsername, but then the sync examples (https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html) use "mail" as the userNameAttributes.

If you sync groups with "mail" but your userids are "uid", you end up with a mismatch, and OpenShift won't properly associate the users with the group. For example, if your group contains a username of `foo@example.com` but the real username in the system is just `foo`, even if `foo`'s group is assigned rights to a project, foo won't see them.
