### ISSUE TITLE
v1.DeploymentConfig Schema envFrom

### ISSUE THREAD

**Issue by Setheck** [openshift/openshift-docs#14353]
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/master/rest_api/oapi/v1.DeploymentConfig.adoc#object-schema

### What needs fixing?
The spacing of the children of `envFrom` is confusing. The hyphen of the `name` field of configMapRef should be on the reference to secretRef see attached screenshot

<img width="237" alt="Screen Shot 2019-04-04 at 4 04 15 PM" src="https://user-images.githubusercontent.com/402885/55594200-8b8fa780-56f3-11e9-987a-b9f08da7aa04.png">

**Comment by Setheck** [comment]
Here is the location from the top
```yml
spec:
  template:
    spec:
      containers:
        envFrom:
            <screenshot is of here>
```
