### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/cluster-autoscaler.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#14535]
### Which section(s) is the issue in?

The section `Creating the Launch Configuration and Auto Scaling group`

There are missing configurations and steps which it needed to work cluster-autoscaler well.

### What needs fixing?

Since Oct. 2018, a credential accessing Red Hat Container Catalog is required. Also AWS credential for atomic-openshift-node is required therefore It should have additional steps as follow:

* Fetch docker.config from a master node
```
ansible -i <Ansible Inventory file> masters[0] -m fetch -a "src=/var/lib/origin/.docker/config.json dest=./dockerconfig.json flat=yes"
```

* Fetch atomic-openshift-node's sysconfig file  from a node
```
ansible -i <Ansible Inventory file> nodes -m fetch -a "src=/etc/sysconfig/atomic-openshift-node dest=./atomic-openshift-node flat=yes" 
```

* user-data.txt should be as follow:

```
cat <<EOF > user-data.txt
#cloud-config
write_files:
- path: /root/openshift_bootstrap/openshift_settings.yaml
  owner: 'root:root'
  permissions: '0640'
  content: |
    openshift_node_config_name: node-config-compute
- path: /etc/origin/node/bootstrap.kubeconfig
  owner: 'root:root'
  permissions: '0640'
  encoding: b64
  content: |
    `base64 ./bootstrap.kubeconfig | sed '2,$s/^/    /'`
- path: /var/lib/origin/.docker/config.json
  owner: 'root:root'
  permissions: '0644'
  encoding: b64
  content: |
    `base64 ./dockerconfig.json | sed '2,$s/^/    /'`
- path: /etc/sysconfig/atomic-openshift-node
  owner: 'root:root'
  permissions: '0644'
  encoding: b64
  content: |
    `base64 ./atomic-openshift-node | sed '2,$s/^/    /'`
runcmd:
- [ ansible-playbook, /root/openshift_bootstrap/bootstrap.yml]
- [ systemctl, restart, systemd-hostnamed]
- [ systemctl, restart, NetworkManager]
- [ systemctl, enable, atomic-openshift-node]
- [ systemctl, start, atomic-openshift-node]
EOF
```
