### ISSUE TITLE
[enterprise-4.1] The indent of install-config.yaml is incorrect in installation-bare-metal-config-yaml.adoc

### ISSUE THREAD

**Issue by bmeng** [openshift/openshift-docs#14707]
### Which section(s) is the issue in?
It is:
```
apiVersion: v1
baseDomain: example.com <1>
compute:
- name: worker
  replicas: 0 <2>
controlPlane:
  name: master
  replicas: 3
metadata:
  name: test <3>
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14 <4>
    hostPrefix: 23 <5>
networkType: OpenShiftSDN
serviceNetwork: <6>
- 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths": ...}' <7>
sshKey: 'ssh-ed25519 AAAA...' <8>
```

### What needs fixing?
Should be:
<pre>
apiVersion: v1
baseDomain: example.com <1>
compute:
- name: worker
  replicas: 0 <2>
controlPlane:
  name: master
  replicas: 3
metadata:
  name: test <3>
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14 <4>
    hostPrefix: 23 <5>
<b>  networkType: OpenShiftSDN
  serviceNetwork: <6>
  - 172.30.0.0/16</b>
platform:
  none: {}
pullSecret: '{"auths": ...}' <7>
sshKey: 'ssh-ed25519 AAAA...' <8>
</pre>
