### ISSUE TITLE
Need to change the liveness/readiness probe scheme as part of securing the registry

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#1500]
https://github.com/openshift/openshift-docs/blob/master/install_config/install/docker_registry.adoc#securing-the-registry

When changing a registry to serve over TLS, in the deploymentconfig, change the livenessProbe and readinessProbe scheme from `HTTP` to `HTTPS`:
```
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTPS
            ...
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTPS
            ...
```
