### ISSUE TITLE
[enterprise-4.1] Edit suggested in file builds/triggering-builds-build-hooks.adoc

### ISSUE THREAD

**Issue by rdutta** [openshift/openshift-docs#15481]
### Which section(s) is the issue in?
**Webhook triggers**

### What needs fixing?

Need an example of yaml template format for manually inserting triggers, e.g.

```
- kind: "BuildConfig"
  spec:
    triggers:
      - type: "Bitbucket"
      bitbucket:
        secretReference:
          name: "webhook-secret"
```
I could not find any reference to this in the documentation.

### Other
Could also do with a note explaining that the web ui offers to generate a WebHookSecretKey
