### ISSUE TITLE
destinationDir absolute path

### ISSUE THREAD

**Issue by AliKarami** [openshift/openshift-docs#15735]
### Which section(s) is the issue in?

build_inputs -> using-secrets-in-the-buildconfig (Adding Input Secrets)

### What needs fixing?

in the buildConfig example, the value of destinationDir is `/etc`:
```
source:
  git:
    uri: https://github.com/openshift/nodejs-ex.git
  secrets:
    - secret:
        name: secret-npmrc
      destinationDir: /etc
```
while OKD only supports relative path for `destinationDir` here.
