### ISSUE TITLE
[enterprise-4.2] Edit suggested in file nodes/clusters/nodes-cluster-overcommit.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#17574]
### Which section(s) is the issue in?

Disabling or enforcing CPU limits using CPU CFS quotas

4.2 link:
https://docs.openshift.com/container-platform/4.2/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-overcommit-node-enforcing_nodes-cluster-overcommit

4.1 link:
https://docs.openshift.com/container-platform/4.1/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-overcommit-node-enforcing_nodes-cluster-overcommit

### What needs fixing?

The correct parameter for disabling cpu cfs quota is `cpuCFSQuota`. So we need to fix it in both 4.1 & 4.2 link shared above.

Correct config:

```
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: enable-cpu-units 
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: small-pods 
  kubeletConfig:
    cpuCFSQuota: false
```
