### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/host_preparation.adoc

### ISSUE THREAD

**Issue by Koma-Andrea** [openshift/openshift-docs#18091]
### Which section(s) is the issue in?
Minimum RHEL version required

### What needs fixing?
The minumum version required from 3.11.153 is 7.5 as stated in the installation playbook:
```yaml
  - name: Ensure minimum kernel version
    fail:
      msg: |
        The installed kernel version does not meet the required minimum for RHEL {{ ansible_facts.distribution_version  }}.
        Please update the kernel before continuing.
        Minimum Kernel Version: {{ minimum_kernel_version[ansible_facts.distribution_version] }}
        Installed Kernel Version: {{ ansible_facts.kernel }}
        Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1749024
    when:
    - ansible_facts.distribution == "RedHat"
    - ansible_facts.distribution_version in minimum_kernel_version
    - ansible_facts.kernel is version_compare(minimum_kernel_version[ansible_facts.distribution_version], '<')
    vars:
      minimum_kernel_version:
        "7.5": "3.10.0-862.31.1"
        "7.6": "3.10.0-957.27.2"
        "7.7": "3.10.0-1062"
```
See the bugzilla for this reference: [BZ1749024](https://bugzilla.redhat.com/show_bug.cgi?id=1749024)
