### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by smossber** [openshift/openshift-docs#18109]
### Which section(s) is the issue in?
Section 5, Create a cluster logging instance

### What needs fixing?
A suggestion for improvement. 

The documentation mentions
```
This default cluster logging configuration should support a wide array of environments. Review the topics on tuning and configuring the cluster logging components for information on modifications you can make to your cluster logging cluster.
``` 
In the example a lot of items are commented with numeral references.
However, there is none that points out the storage class, which is gp2 in the example.
The doc could be _improved_ by also highlighting the storage class, and a mention on how to find your storage class maybe.
```
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    elasticsearch:
      nodeCount: 3 
      storage:
        storageClassName: gp2   <------ this guy
        size: 200G
```
