### ISSUE TITLE
[enterprise-4.2] Edit suggested in file metering/configuring-metering/metering-configure-hive-metastore.adoc

### ISSUE THREAD

**Issue by brokenpip3** [openshift/openshift-docs#18721]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/metering/configuring-metering/metering-configure-hive-metastore.html#metering-use-mysql-or-postgresql-for-hive_metering-configure-hive-metastore

### What needs fixing?

The example spec yaml for configuring a db (mysql or pg) for hive metastore is:
```

spec:
  hive:
    spec:
      config:
        url: "jdbc:mysql://mysql.example.com:3306/hive_metastore"
        driver: "com.mysql.jdbc.Driver"
        username: "REPLACEME"
        password: "REPLACEME"

```

instead it should be:

```
spec:
  hive:
    spec:
      config:
        db: ### <--- FIX
          url: "jdbc:mysql://mysql.example.com:3306/hive_metastore"
          driver: "com.mysql.jdbc.Driver"
          username: "REPLACEME"
          password: "REPLACEME"
```

as pointed here: https://github.com/operator-framework/operator-metering/blob/master/Documentation/configuring-hive-metastore.md#use-mysql-for-the-hive-metastore-database
(this is mysql example but postgresql section need the fix as well)
