### ISSUE TITLE
[enterprise-4.2] Edit suggested in file storage/persistent-storage/persistent-storage-gce.adoc

### ISSUE THREAD

**Issue by funixz** [openshift/openshift-docs#18797]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/storage/persistent-storage/persistent-storage-gce.html

### What needs fixing?

The installer-created storage class for GCE leaves PVCs in pending and doesn't work.
I've found the following will make the GCE volumes work...
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/gce-pd
parameters:
  replication-type: none
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
Please provide working storage class reference, such as the above, or modify the yaml created by the installer for GCE clusters.
