### ISSUE TITLE
[enterprise-4.2] Edit suggested in file web-console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by briantward** [openshift/openshift-docs#18890]
### Which section(s) is the issue in?

Console object is wrong.  Should look like below. Spec should be at same indent as metadata.  Indents should be two spaces not three. Likely needs backporting to 4.1 docs

### What needs fixing?

```
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    customProductName: My Console
      customLogoFile:
        name: console-custom-logo
        key: console-custom-logo.png
```

**Comment by briantward** [comment]
so much for github preserving spaces... woops

```
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
   name: cluster
spec:
  customization:
    customProductName: My Console
    customLogoFile:
      name: console-custom-logo
      key: console-custom-logo.png
```
