### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by welshstew** [openshift/openshift-docs#18905]
### Which section(s) is the issue in?

Installing the Cluster Logging and Elasticsearch Operators

3.  Install the Cluster Logging Operator using the OpenShift Container Platform web console for best results:
a. In the OpenShift Container Platform web console, click Operators → OperatorHub.
b. Choose Cluster Logging from the list of available Operators, and click Install.
c. On the Create Operator Subscription page, under A specific namespace on the cluster select openshift-logging. Then, click Subscribe.

### What needs fixing?

This documentation requires that the user uses the web interface, would be good to have an alternative to show what yaml to create.  

`oc create -f cluster-logging-og.yaml`
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterLogging.v1.logging.openshift.io
  generateName: openshift-logging-
spec:
  targetNamespaces:
  - openshift-logging
```
`oc create -f cluster-logging-subscription.yaml`
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: "4.2"
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
