### ISSUE TITLE
[enterprise-4.3] Edit suggested in file web-console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by andreasottosson** [openshift/openshift-docs#19600]
### Which section(s) is the issue in?

Adding a custom logo and product name

### What needs fixing?

YAML indentation in step 2,

```
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    customProductName: My Console
      customLogoFile:
        name: console-custom-logo
        key: console-custom-logo.png
```
should be
```
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    customProductName: My Console
    customLogoFile:
      name: console-custom-logo
      key: console-custom-logo.png
```
