### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#19813]
### Which section(s) is the issue in?
Installing the Cluster Logging and Elasticsearch Operators

### What needs fixing?
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: "elasticsearch-"
  namespace: "openshift-operators-redhat" 
spec:
  channel: "4.2" 
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"

will not work, missing metadata: name:

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: "elasticsearch-"
  namespace: "openshift-operators-redhat" 
  name: "elasticsearch-operator"  <<<<<<
spec:
  channel: "4.2" 
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"

**Comment by mburke5678** [comment]
@aelicieguo I am finding that if you don't supply a name, the installer assigns a name automatically. But, it probably makes sense to add a name for clarity. 
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: "elasticsearch-"
  namespace: "openshift-operators-redhat"
spec:
  channel: "4.3"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"
```

```
$ oc create -f eo-sub.yaml
subscription.operators.coreos.com/elasticsearch-jd68t created
$ oc get subscription.operators.coreos.com --all-namespaces
NAMESPACE                    NAME                  PACKAGE                  SOURCE             CHANNEL
openshift-operators-redhat   elasticsearch-jd68t   elasticsearch-operator   redhat-operators   4.3
```
