### ISSUE TITLE
[enterprise-4.3] Edit suggested in file migration/migrating_4_1_4/configuring-replication-repository.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#19823]
### Which section(s) is the issue in?
Configuring a replication repository

### What needs fixing?
In this section we describe you could also use a Generic S3 object storage.
It would be useful when you would enter a chapter how to create one.

It is very easy to create a Minio one with the following yaml.

```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations: {}
  name: minio-access-secrets
stringData:
  minioSecret: minio123
  minioAccessKey: minio
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-server
spec:
  type: NodePort
  selector:
    app: minio-server
  ports:
    - name: web
      port: 80
      targetPort: 9000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: minio
spec:
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
spec:
  selector:
    matchLabels:
      app: minio-server
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioSecret
          image: minio/minio
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
              name: web
          volumeMounts:
            - name: home
              mountPath: /data
            - name: config
              mountPath: /root/.minio
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home-claim
        - name: config
          persistentVolumeClaim:
            claimName: `minio-config-claim`
```
Later you will need the url of the route for the minio.apps.mydomain.com
The access and secret key will be in the created secret (here minio/minio123)
And you have to create a bucket on the UI, e.g. click on the right bottom "+" and type "mybucket".
Done.
