### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring-networkpolicy.adoc

### ISSUE THREAD

**Issue by janehojy** [openshift/openshift-docs#20483]
### Which section(s) is the issue in?

[Configuring multitenant isolation using NetworkPolicy](https://docs.openshift.com/container-platform/4.3/networking/configuring-networkpolicy.html#nw-networkpolicy-multitenant-isolation_configuring-networkpolicy-plugin )

### What needs fixing?

Multitenant isolation is missing allow from same namespace

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {}
```

**Comment by jboxman** [comment]
Hi @zhaozhanqi, do you know if we also need the above network policy to get the same behavior as OpenShift SDN _multitenant_ mode offers?

Thanks!

**Comment by zhaozhanqi** [comment]
@jboxman no need for multitenant mode. it's for `networkpolicy` mode only.

**Comment by jboxman** [comment]
@zhaozhanqi, but do I need to use all 3 of these policies, or just the first 2?

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {}
```
