### ISSUE TITLE
[enterprise-4.3] Edit suggested in file storage/persistent_storage/persistent-storage-local.adoc

### ISSUE THREAD

**Issue by janehojy** [openshift/openshift-docs#20482]
### Which section(s) is the issue in?

Persistent storage using local volumes > [Using tolerations with Local Storage Operator Pods](https://docs.openshift.com/container-platform/4.3/storage/persistent_storage/persistent-storage-local.html#local-tolerations_persistent-storage-local)

### What needs fixing?

The sample yaml file is insufficient to create the CR. 

```
  apiVersion: "local.storage.openshift.io/v1"
  kind: "LocalVolume"
  metadata:
    name: "local-disks"
    namespace: "local-storage"
  spec:
    tolerations:
      - key: localstorage 
        operator: Equal 
        value: "localstorage" 
```

```
$ oc create -f localvolume-cr.yaml 
The LocalVolume "local-disks" is invalid: spec.storageClassDevices: Required value
```

As the error suggests, `spec.storageClassDevices` is needed in the yaml file.
