### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/config/cluster-logging-tolerations.adoc

### ISSUE THREAD

**Issue by janehojy** [openshift/openshift-docs#20485]
### Which section(s) is the issue in?

[Using tolerations to control cluster logging pod placement](https://docs.openshift.com/container-platform/4.2/logging/config/cluster-logging-tolerations.html) > Using tolerations to control the Elasticsearch Pod placement

### What needs fixing?

Under the section "Using tolerations to control the Elasticsearch Pod placement"

```
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      tolerations:
      - key: "1"    <===== wrong key
        operator: "Exists"  
        value: "elasticsearch"   <===== wrong value
        effect: "NoExecute"  
        tolerationSeconds: 6000  
```

The toleration should be changed to the following for it to match the taint added in the earlier step 
(`$ oc adm taint nodes node1 elasticseach=node:NoExecute`)

```
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      tolerations:
      - key: "elasticsearch"  <===== correct key
        operator: "Exists"  
        value: "node"    <===== correct value
        effect: "NoExecute"  
        tolerationSeconds: 6000  
```
