### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by janehojy** [openshift/openshift-docs#20480]
### Which section(s) is the issue in?

Deploying cluster logging > Install the Elasticsearch Operator using the CLI 

### What needs fixing?

Under section 2, **Install the Elasticsearch Operator by creating the following objects:**

c. Create a Subscription object YAML file (for example, eo-sub.yaml) to subscribe a Namespace to an Operator.

Example subscription
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "elasticsearch-operator"
  namespace: "openshift-operators-redhat" 
spec:
  channel: "4.3" 
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"
```

it should be stated clearly that `source` has to match the name used in the CatalogSource object.

Especially for disconnected clusters, most people would have named it `my-operator-catalog` and not `redhat-operators`, if they followed the documentation [here](https://docs.openshift.com/container-platform/4.3/operators/olm-restricted-networks.html#olm-restricted-networks-operatorhub_olm-restricted-networks) which says:

```
4. Create a CatalogSource object that references your catalog image.
a. Modify the following to your specifications and save it as a catalogsource.yaml file:

> apiVersion: operators.coreos.com/v1alpha1
> kind: CatalogSource
> metadata:
>   name: my-operator-catalog
>   namespace: openshift-marketplace
> spec:
>   sourceType: grpc
>   image: <registry_host_name>:<port>/olm/redhat-operators:v1 
>   displayName: My Operator Catalog
>   publisher: grpc
```

In which case, `source: "redhat-operators"` in the eo-sub.yaml file would not work for them. It has to be `source: my-operator-catalog`.

**Comment by janehojy** [comment]
Same goes for the clo-sub.yaml file if [installing the Cluster Logging Operator using the CLI](https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html#cluster-logging-deploy-clo-cli_cluster-logging-deploying).

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging 
spec:
  channel: "4.3" 
  name: cluster-logging
  source: redhat-operators  <========== needs to be stated clearly it must be named according to the CatalogSource name, in which case `my-operator-catalog` for those who followed the disconnected OLM steps in the docs
  sourceNamespace: openshift-marketplace
```
