### ISSUE TITLE
[enterprise-4.3] Edit suggested in file registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc

### ISSUE THREAD

**Issue by dglib** [openshift/openshift-docs#20547]
### Which section(s) is the issue in?
Configuring registry storage for VMware vSphere
Step 4a

### What needs fixing?

```
spec:
  accessModes:
    ReadWriteMany
    capacity:
      storage: 100Gi
  nfs:
    path: /registry
```
Change to

```
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /
```
For NFSv4 support, the path must be "path: /" since the /etc/exports example includes the option "fsid=0" which root's the exported share.
