### ISSUE TITLE
[enterprise-4.4] Edit suggested in file service_mesh/service_mesh_day_two/prepare-to-deploy-applications-ossm.adoc

### ISSUE THREAD

**Issue by btannous** [openshift/openshift-docs#22215]
### Which section(s) is the issue in?
The example app `sleep` doesn't actually work.  There are a few things wrong.

original here:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
```

The error when applying the above yaml:
```bash
The Deployment "sleep" is invalid: 
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"app":"sleep"}: `selector` does not match template `labels`
```

### What needs fixing?
This works:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sleep
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleep
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
status: {}
```

The blank fields can be deleted, but they were generated w/ the `oc create deployment --image REPLACE sleep --dry-run -oyaml` and don't hurt to have them.
But it seems like the main issue is the selector needing to be there.
