### ISSUE TITLE
[enterprise-4.4] Edit suggested in SCC

### ISSUE THREAD

**Issue by Koma-Andrea** [openshift/openshift-docs#22347]
### Which section(s) is the issue in?
MustRunAsRange is not documented anywhere but mentioned costantly:
The only place where I found the correct syntax is in an example in doc version 3.2 and in the sourcecode:
```
runAsUser:
  type: MustRunAsRange 
  uidRangeMax: 1000100001 
  uidRangeMin: 1000100001
```
[SourceCode](https://github.com/openshift/apiserver-library-go/blob/release-4.4/pkg/securitycontextconstraints/user/mustrunasrange.go
)
### What needs fixing?
We should document the CRD options or at least enumerate them.
