### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/pruning-objects.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#22376]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html#pruning-images_pruning-objects

### What needs fixing?
The timestamps shown are wrong! There's the Z missing at the end of the timestamp! It's Zulu time -> UTC!

**Comment by jboxman** [comment]
That's odd; We wouldn't have intentionally altered that. Maybe in 2019 the output was different? I have `Z` now:

```
status:
  conditions:
  - lastTransitionTime: "2020-05-02T05:33:08Z"
    message: Pruner CronJob has been created
    reason: Ready
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-02T05:32:32Z"
    message: Pruner completed successfully
    reason: Complete
    status: "False"
    type: Failed
  - lastTransitionTime: "2020-05-02T05:32:32Z"
    message: The pruner job has been suspended.
    reason: Suspended
    status: "False"
    type: Scheduled
  observedGeneration: 1
```
