### ISSUE TITLE
[enterprise-4.4] Edit suggested in file networking/configuring-networkpolicy.adoc

### ISSUE THREAD

**Issue by JuozasA** [openshift/openshift-docs#23080]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/networking/configuring-networkpolicy.html#nw-networkpolicy-multitenant-isolation_configuring-networkpolicy-plugin
**"Configuring multitenant isolation using NetworkPolicy"**

When this procedure is being followed, pods within the same project won't be able to communicate. 
### What needs fixing?

Aditional rule is required to allow that:

_To make Pods accept connections from other Pods in the same project, but reject all other connections from Pods in other projects, add the following NetworkPolicy object:_
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {}
```
