### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/pods/nodes-pods-autoscaling.adoc

### ISSUE THREAD

**Issue by garethahealy** [openshift/openshift-docs#24646]
### Which section(s) is the issue in?
The first v2 HPA yaml mixes metric types:

```
metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageValue: 500m
```

### What needs fixing?
k8s docs (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) says its:

```
You can also specify resource metrics in terms of direct values, instead of as percentages of the requested value, by using a target.type of AverageValue instead of Utilization, and setting the corresponding target.averageValue field instead of the target.averageUtilization.
```

So the above, needs to be changed to:

```
metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: **AverageValue** 
        averageValue: 500m
```
