### ISSUE TITLE
[enterprise-4.4] Issue in file updating/updating-restricted-network-cluster.adoc

### ISSUE THREAD

**Issue by pdfruth** [openshift/openshift-docs#24813]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/updating/updating-restricted-network-cluster.html#update-configuring-image-signature

The same also applies to the equivalent page in the Openshift 4.5 documentation at;
https://docs.openshift.com/container-platform/4.5/updating/updating-restricted-network-cluster.html#update-configuring-image-signature

### What needs fixing?
Step 8 of the procedure states;

> 8. Create the ConfigMap:

The example command following step 8 contains;
```
cat >checksum-${OCP_RELEASE_NUMBER}.yaml <<EOF
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: release-image-${OCP_RELEASE_NUMBER}
   namespace: openshift-config-managed
   labels:
     release.openshift.io/verification-signatures: ""
 binaryData:
   ${DIGEST_ALGO}-${DIGEST_ENCODED}: ${SIGNATURE_BASE64}
 EOF
```

This command does not work as-is.
The problem is, each line of the yaml following the cat command, and the terminating EOF, are all preceded with a space character.
The leading space character should be removed from each line of yaml, and the terminating EOF.

So, it _should_ look like this instead;
```
cat >checksum-${OCP_RELEASE_NUMBER}.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-image-${OCP_RELEASE_NUMBER}
  namespace: openshift-config-managed
  labels:
    release.openshift.io/verification-signatures: ""
binaryData:
  ${DIGEST_ALGO}-${DIGEST_ENCODED}: ${SIGNATURE_BASE64}
EOF
```
