### ISSUE TITLE
[enterprise-4.5] Installation for IBM Z is missing "architecture: s390x"

### ISSUE THREAD

**Issue by e-desouza** [openshift/openshift-docs#26122]
### Which section(s) is the issue in?

Installation on IBM Z, specifically the install yaml: https://docs.openshift.com/container-platform/4.5/installing/installing_ibm_z/installing-ibm-z.html#installation-bare-metal-config-yaml_installing-ibm-z

This leads to clients pulling amd64 binaries for z and installation failing with "binary exec errors" from Go.

### What needs fixing?

```yaml
..
apiVersion: v1
baseDomain: <domain>
compute:
- architecture: s390x << missing
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: s390x << missing
  hyperthreading: Enabled
  name: master
  replicas: 3
..
```
