### ISSUE TITLE
[enterprise-4.5] Issue in file storage/persistent_storage/persistent-storage-local.adoc

### ISSUE THREAD

**Issue by chris-short** [openshift/openshift-docs#26573]
### Which section(s) is the issue in?
Installing the Local Storage Operator

### What needs fixing?
The YAML example has bad spacing here's what I used to create everything
```
  apiVersion: v1
  kind: Namespace
  metadata:
    name: local-storage
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: local-operator-group
  namespace: local-storage
spec:
  targetNamespaces:
    - local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: local-storage
spec:
  channel: "4.6"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```

But, this still did not end up with a local-storage pod running in 4.6.
