### ISSUE TITLE
[enterprise-4.6] Issue in file networking/ovn_kubernetes_network_provider/configuring-egress-firewall-ovn.adoc

### ISSUE THREAD

**Issue by ghurel-rh** [openshift/openshift-docs#27346]
### Which section(s) is the issue in?

- EgressFirewall rules > Egress policy rule stanza
- Example EgressFirewall CR objects > second example

### What needs fixing?

The indentation of the field "ports" is wrong: it should be at the same level than "to".

```
➜ oc explain egressfirewall.spec.egress
KIND:     EgressFirewall
VERSION:  k8s.ovn.org/v1

RESOURCE: egress <[]Object>

DESCRIPTION:
     a collection of egress firewall rule objects

     EgressFirewallRule is a single egressfirewall rule object

FIELDS:
   ports	<[]Object>
     ports specify what ports and protocols the rule applies to

   to	<Object> -required-
     to is the target that traffic is allowed/denied to

   type	<string> -required-
     type marks this as an "Allow" or "Deny" rule
``` 

so, in the documentation, it should be:

```
egress:
- type: <type> 
  to: 
    cidrSelector: <cidr> 
  ports: 
      ...
```

and

```
apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
  name: default
spec:
  egress:
  - type: Deny
    to:
      cidrSelector: 172.16.1.1
    ports:
    - port: 80
      protocol: TCP
    - port: 443
```

All the best,
Gaëtan
