### ISSUE TITLE
[enterprise-4.6] Issue in file storage/persistent_storage/persistent-storage-local.adoc

### ISSUE THREAD

**Issue by ptrnull** [openshift/openshift-docs#28156]
Installing the Local Storage Operator

### Which section(s) is the issue in?
The "Example openshift-local-storage.yaml" code block has an error in the yaml separator '---'.

### What needs fixing?
The blank spaces before the yaml separator should be removed, should be like:
```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: local-operator-group
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: <channel_version> 
  installPlanApproval: Automatic 
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
