### ISSUE TITLE
[enterprise-4.6] Issue in file networking/ovn_kubernetes_network_provider/assigning-egress-ips-ovn.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#28357]
### Which section(s) is the issue in?

Assigning an IP address to a namespace

### What needs fixing?

It would be useful to clarify the point that the namespaceSelector doesn't directly reference the actual name of the project.

The example:

```
  namespaceSelector:
    matchLabels:
      name: project1
```

implies that the match is made based on the project name. However `matchLabels` matches on labels, not on the metadata fields. So this example won't work unless the namespace is also labelled, such as with:

```
oc label ns/project1 name=project1
```

In hindsight it becomes obvious that `matchLabels` would depend on labels, but it would be more clear to call out the labeling requirement.

**Comment by jboxman** [comment]
This is specifically?

```yaml
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egress-project1
spec:
  egressIPs:
  - 192.168.127.10
  - 192.168.127.11
  namespaceSelector:
    matchLabels:
      name: project1 <-- this
```

Interesting. So this matches a namespace based on whatever metadata is assigned to it, but not the `name` of it?

Would something like `app: example1` be a little more clear?

**Comment by ChetRHosey** [comment]
Agreed, something like "app: example1" would be more clear.

It matches based on labels specifically, not the more general metadata contents. Unfortunately that does mean metadata.name can't be used for matching.

It might also be useful to include a corresponding example project with the matching label, such as the one below that would match your suggested "app: example1".

```
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: project1
  labels:
    app: example1
```

I might even call the EgressIP object "egress-example1-app" or something that hints toward the selector rather than the project's name.

Thanks for reviewing.
