### ISSUE TITLE
Enabling strict mTLS across the mesh does not enable strict mode

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#28869]
### Which section(s) is the issue in?

Enabling strict mTLS across the mesh
https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/ossm-security.html#ossm-security-enabling-strict-mtls_ossm-security

The docs says "Enabling strict mTLS" by setting `spec.security.controlPlane.mtls` to true in your ServiceMeshControlPlane resource. But it enables __permissive__ mode not __strict__ mode.

### What needs fixing?

Edit `PeerAuthentication` in the namespace where SMCP is deployed.

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: <NAMESPACE where SMCP is deployed>
spec:
  mtls:
    mode: STRICT
```
