### ISSUE TITLE
[enterprise-4.7] A sample CustomResource file has a syntax error in Installing OpenShift Logging

### ISSUE THREAD

**Issue by KEITA-Diego-Y** [openshift/openshift-docs#29909]
### Which section(s) is the issue in?

OCP 4.7 (latest as of 28-Feb-2021)

A sample yaml file of OpenShift Logging instance

https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying

### What needs fixing?

The part of the sample file seems to be wrong in syntax.

```
spec:
...
  logStore:
    type: "elasticsearch"  
...
    elasticsearch:
...
     proxy: 
        limits:
          memory: 256Mi
        requests:
           memory: 256Mi
```

It should be the following, because when I apply the sample file, by "$oc create -f [the sample file]", the command returned the error.

```
spec:
...
  logStore:
    type: "elasticsearch"  
...
    elasticsearch:
...
     proxy:
        resources: 
            limits:
              memory: 256Mi
            requests:
               memory: 256Mi
```

```
$ oc create -f [the sample CustomResrouce yaml file]
The ClusterLogging "instance" is invalid: spec.logStore.elasticSearch.proxy.resources: Required Vaule
```

It's just a small mistake but just for sure.
(I googled and search in the issue list but not found anything on this topic.)
