### ISSUE TITLE
[enterprise-4.7] Issue in file storage/container_storage_interface/persistent-storage-csi-snapshots.adoc

### ISSUE THREAD

**Issue by JuozasA** [openshift/openshift-docs#29919]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/storage/container_storage_interface/persistent-storage-csi-snapshots.html#persistent-storage-csi-snapshots-restore_persistent-storage-csi-snapshots

### What needs fixing?

`dataSource` block `apiGroup` section should not have `/v1` suffix since it defines the version of the group. Should be like this:
```
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: mysnap
```

Otherwise the whole block is being ignored and the restore does not work
