### ISSUE TITLE
[enterprise-4.7] Issue in file storage/persistent_storage/persistent-storage-local

### ISSUE THREAD

**Issue by tumido** [openshift/openshift-docs#29927]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/storage/persistent_storage/persistent-storage-local.html#local-storage-install_persistent-storage-local

### What needs fixing?

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: <channel_version> 
  installPlanApproval: Automatic 
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```

`Subscription` resource should provide guidance on channel selection like it does for other `Subscription`s across the board. Documenting the channel as `<channel_version>` is not helpful and doesn't allow users to install via CLI unless they look up the channel version somewhere (in UI).
