### ISSUE TITLE
[dedicated] Issue in file logging/dedicated-cluster-deploying.adoc

### ISSUE THREAD

**Issue by RiRa12621** [openshift/openshift-docs#30300]
### Which section(s) is the issue in?

```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed" 
  logStore:
    type: "elasticsearch" 
    retentionPolicy: 
      application:
        maxAge: 7d
      infra:
        maxAge: 0d
      audit:
        maxAge: 0d
    elasticsearch:
      nodeCount: 3 
      storage:
        storageClassName: gp2 
        size: "200Gi"
      redundancyPolicy: "SingleRedundancy"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      resources: 
        request:
          memory: 8G
  visualization:
    type: "kibana" 
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/worker: ""
  curation:
    type: "curator"
    curator:
      schedule: "30 3 * * *" 
      nodeSelector:
        node-role.kubernetes.io/worker: ""
  collection:
    logs:
      type: "fluentd" 
      fluentd: {}
      nodeSelector:
        node-role.kubernetes.io/worker: ""
```

### What needs fixing?

``` 
     infra:
        maxAge: 0d
      audit:
        maxAge: 0d
```

needs to be adjusted to because of https://bugzilla.redhat.com/show_bug.cgi?id=1936998#c2

```
      infra:
        maxAge: 1h
      audit:
        maxAge: 1h
```
