### ISSUE TITLE
[enterprise-4.7] Issue in file cicd/pipelines/understanding-openshift-pipelines.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#30559]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/cicd/pipelines/understanding-openshift-pipelines.html#about-pipelines_understanding-openshift-pipelines

### What needs fixing?
Small grammatical error in pipelines section. The description says "image to be build from the code". Needs to be "image to be built from the code".

Here is the code in the pipelines section I am referring to (line 21):

```
apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: build-and-deploy 
spec: 
  workspaces: 
  - name: shared-workspace
  params: 
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "pipelines-1.3"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks: 
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image 
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: apply-manifests 
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter: 
    - build-image
  - name: update-deployment
    taskRef:
      name: update-deployment
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
```
