### ISSUE TITLE
[enterprise-4.6] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws-network-load-balancer.adoc

### ISSUE THREAD

**Issue by klaphi** [openshift/openshift-docs#31149]
### Which section(s) is the issue in?

Configuring an Ingress Controller Network Load Balancer on an existing AWS cluster

### What needs fixing?
Please describe also howto replace the existing openshift ingress, because on a existing cluster it is not allowed to have more then one ingress.

Something like:
```
cat ingresscontroller-aws-nlb.yaml

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  domain: <cluster-domain>
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal
      providerParameters:
        type: AWS
        aws:
          type: NLB
```
Replace the default ingress with a new one that uses the NLB instead of CLB:

```
oc --namespace openshift-ingress-operator delete ingresscontrollers.operator.openshift.io default && oc create -f ingresscontroller-aws-nlb.yaml
```
