### ISSUE TITLE
[enterprise-4.7] Issue in file service_mesh/v2x/ossm-custom-resources.adoc

### ISSUE THREAD

**Issue by domcar** [openshift/openshift-docs#31735]
### Which section(s) is the issue in?
it looks to me that the documentation is wrong, it still uses maistra v1 definition.
I cannot apply the "Example ServiceMeshControlPlane resource" configuration because many of those fields are not recognized.
Example: 
```
  addons:
    grafana:
      enabled: true
      install:
        config:
          env: {}
          envSecrets: {}
        persistence:
          storageClassName: ""
          accessMode: ReadWriteOnce
          capacity: 5Gi
```
The capacity is not recognized

or 
```
spec:
  kiali:
    enabled: true
    dashboard:
      viewOnlyMode: false
      grafanaURL:  "https://grafana-istio-system.127.0.0.1.nip.io"
    ingress:
      enabled: true
````
under "spec" is not possible to use this and if I add the grafanaURL in the addon section (see above) it doesn't recognize this field

### What needs fixing?
Update documentation
