### ISSUE TITLE
[enterprise-4.7] Example Deployment Strategy is invalid

### ISSUE THREAD

**Issue by dmc5179** [openshift/openshift-docs#32045]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/applications/deployments/deployment-strategies.html#deployments-rolling-strategy_deployment-strategies

### What needs fixing?

This example uses strategy "Rolling" which is invalid. The strategy is called "RollingUpdate"

```
strategy:
  type: Rolling
  rollingParams:
    updatePeriodSeconds: 1 
    intervalSeconds: 1 
    timeoutSeconds: 120 
    maxSurge: "20%" 
    maxUnavailable: "10%" 
    pre: {} 
    post: {}
```

```
spec.strategy: Unsupported value: apps.DeploymentStrategy{Type:"Rolling", RollingUpdate:(*apps.RollingUpdateDeployment)(nil)}: supported values: "Recreate", "RollingUpdate"
```
