### ISSUE TITLE
[enterprise-4.7] Issue in file security/compliance_operator/compliance-operator-raw-results.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#32400]
### Which section(s) is the issue in?
Step 3. Pod Example has an indent issue.
I got the following error message when I created a pod which is used yaml file copied from the document.

```
error: error parsing pod2.yml: error converting YAML to JSON: yaml: line 12: did not find expected '-' indicator
```
### What needs fixing?
The cause of the issue was the yaml file has wrong indent on line 13.

```
apiVersion: "v1"
kind: Pod
metadata:
  name: pv-extract
spec:
  containers:
    - name: pv-extract-pod
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: "/workers-scan-results"
        name: workers-scan-vol
    volumes:
     - name: workers-scan-vol
       persistentVolumeClaim:
         claimName: rhcos4-moderate-worker
```

In the Pod Example, volume field indent should be 2 but not 4. According to Pod schema,
Field `containers` and `volumes` should have the same indent numbers.
