### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_aws/installing-aws-network-customizations.adoc

### ISSUE THREAD

**Issue by pcunning-rh** [openshift/openshift-docs#32623]
### Which section(s) is the issue in?

Many portions of the docs pages where the following IPsec configuration stanza appears 
```
defaultNetwork:
  type: OVNKubernetes
  ovnKubernetesConfig:
    mtu: 1400
    genevePort: 6081
    ipsecConfig: {}
``` 

This code stanza is listed in "installation with network customization "sections such as "installing_aws/installing-aws-network-customizations" and "installing/installing_bare_metal/installing-bare-metal-network-customizations.html"

### What needs fixing?
The default install-config.yaml that is generated from `openshift-install create install-config` contains a default of `networking.networkType: OpenShiftSDN`

While OVNKubernetes is the only IPsec capable network type, it's worth noting in the example configs supplied the `networking.networkType` field should also be changed to `OVNKubernetes`. Otherwise if a user supplies 2 conflicting networkTypes (`networking.networkType: OpenShiftSDN` and `defaultNetwork.type: OVNKubernetes`) the desired end result (IPsec enabled) will not be achieved as OpenShiftSDN is installed as the network type.

### Suggested Fix
Wherever an `OVNKubernetes` config example stanza exists, include the `networking.networkType: OVNKubernetes` sample configuration as well.

FROM:
```
defaultNetwork:
  type: OVNKubernetes
  ovnKubernetesConfig:
    mtu: 1400
    genevePort: 6081
    ipsecConfig: {}
```

TO:
```
networking:
...
  networkType: OVNKubernetes
  ...
defaultNetwork:
  type: OVNKubernetes
  ovnKubernetesConfig:
    mtu: 1400
    genevePort: 6081
    ipsecConfig: {}
```
