### ISSUE TITLE
[enterprise-4.7] Issue in file rest_api/monitoring_apis/alertmanagerconfig-monitoring-coreos-com-v1alpha1.adoc

### ISSUE THREAD

**Issue by samgriek** [openshift/openshift-docs#32782]
### Which section(s) is the issue in?
kind AlertmanagerConfig on AlertManager version 0.21.0 - slack receiver configs.

### What needs fixing?
Trying to set up a slack receiver but after deployment the alertmanager.yaml file does not have a global: slack_api_url causing AlertManager failure on start.

### alertmanager_config.yaml:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alermanager-config
  namespace: my-custom-namespace
  labels:
    alertmanagerConfig: my-alertmanager-config

spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack-receiver'

  receivers:
    - name: 'slack-receiver'
      slackConfigs:
        - apiURL:
            name: 'alertmanager-receiver-secret'
            key: 'SLACK_WEBHOOK_URL'
        - channel: '#my-channel'
```

### resulting alertmanager.yaml in the container:
```
/alertmanager $ cat /etc/alertmanager/config/alertmanager.yaml
route:
  receiver: "null"
  routes:
  - receiver: enterprise-dev-alermanager-config-slack-receiver
    group_by:
    - job
    match:
      namespace: my-namespace
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
receivers:
- name: "null"
- name: my-custom-namespace-alermanager-config-slack-receiver
  slack_configs:
  - api_url: https://hooks.slack.com/services/XXXXXXXXXXXXXXX
  - channel: '#my-channel'
templates: []
/alertmanager $ 
```

### config loader log:
```
level=error ts=2021-05-25T07:24:18.037Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="no global Slack API URL set"
```

Suggestions:  
1. Allow for specifying the 'global' node in the API - Should allow anything the user wants to do here because it could be that the instance of alertmanager is project specific and therefore a global url makes sense.

2. Create a default/null global slack_api_url when a slack receiver is created.

3. Document what versions of alertmanager were considered in the development of the AlertManagerConfig kind in this API.
