### ISSUE TITLE
[enterprise-4.7] Issue in file service_mesh/v2x/ossm-custom-resources.adoc

### ISSUE THREAD

**Issue by ChrisSchneider** [openshift/openshift-docs#33052]
### Which section(s) is the issue in?

[Red Hat OpenShift Service Mesh custom resources](https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/ossm-custom-resources.html#ossm-cr-example_ossm-custom-resources-v2x)

### What needs fixing?

The example shows that `ServiceMeshControlPlane` resources can be set with `spec.proxy.resources`:

```
spec:
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
```

However, according to the [CRD](https://github.com/maistra/olm-metadata/blob/master/manifests/2.0.0/servicemeshcontrolplanes.crd.yaml) I think it should be:

```
spec:
  proxy:
    runtime:
      container:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
```
