### ISSUE TITLE
docs say to use `extenisons.` in EventListner.triggers.interceptors.cel.overlays.key value but that doesnt work

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-docs#34088]
### Which section(s) is the issue in?
I dont know where the Tekton docs live within the OpenShift docs but @Preeticp recomended I open this here.

https://tekton.dev/docs/triggers/eventlisteners/#eventlistener-response in the Overlays section.

### What needs fixing?
The docs show that to set a value for an extension to do:

EventListener
```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: extensions.truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: extensions.branch_name
              expression: "body.ref.split('/')[2]"
```

TriggerBinding
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: test
spec:
  params:
  - name: truncated-sha
    value: $(extensions.truncated_sha)
  - name: branch-name
    value: $(extensions.branch_name)
 ````

But from expermintation with Red Hat OpenShift Pipelines 1.4.1 that doesnt work and gives error. What works is:

EventListener
```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
```

TriggerBinding
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: test
spec:
  params:
  - name: truncated-sha
    value: $(extensions.truncated_sha)
  - name: branch-name
    value: $(extensions.branch_name)
 ````

The difference being dropping the `extensions.` in the EventListener in the overlay key value.

## other

The weird thing is before I upgraded to 1.4.1 this worked as documented, I had to have the `extensions.` in there (dont know what version i was on before, it was pre-ga). But then after upgrading, eventlistener broke and through experimentation I figured this out.

I dont know if this is expected behavior and thus a doc bug, or unexpected behavior and the docs are correct.
