### ISSUE TITLE
[enterprise-4.7] Issue in file web_console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#34311]
### Which section(s) is the issue in?

Adding a custom logo and product name

### What needs fixing?

In example CM yaml, the apiVersion should be `v1`, not `operator.openshift.io/v1`.

```yaml
apiVersion: operator.openshift.io/v1
kind: ConfigMap
metadata:
  name: console-custom-logo
  namespace: openshift-config
data:
  console-custom-logo.png: <base64-encoded_logo> ... 
```
