### ISSUE TITLE
Documentation missing extensionProperties that can be configured in master-config.yaml

### ISSUE THREAD

**Issue by jawnsy** [openshift/openshift-docs#3442]
In the topic " [Customizing the Web Console](https://docs.openshift.org/latest/install_config/web_console_customization.html)", we explain how to create a UI extension.  It's not mentioned on this page, but it's possible to pass arbitrary settings from the `master-config.yaml` file to be used by the extension using the `extensionProperties` mechanism (it nonetheless appears in a generated configuration when using `--write-config`)

Here's an example we're using for OpenShift Online (note the extensionProperties section):

```yaml
assetConfig:
  extensionDevelopment: true
  extensionProperties:
    doc_url: https://docs.openshift.com/online/
    hello: world
    test: thing
  extensionScripts:
  - /home/jawnsy/projects/online/src/github.com/openshift/online/notifications/ui/assets/extensions/online-notifications.js
  - /home/jawnsy/projects/online/src/github.com/openshift/online/devpreview/ui/assets/extensions/online-extensions.js
  extensionStylesheets:
  - /home/jawnsy/projects/online/src/github.com/openshift/online/devpreview/ui/assets/extensions/online-extensions.css
  extensions:
  - name: notifications
    sourceDirectory: /home/jawnsy/projects/online/src/github.com/openshift/online/notifications/ui/assets/extensions/
```

This results in a global variable that can be accessed by the extension; it looks like this:

```javascript
window.OPENSHIFT_EXTENSION_PROPERTIES = {
  doc_url: "https://docs.openshift.com/online/",
  hello: "world",
  test: "thing",
}
```

@jwforres Is this just an oversight in the docs, or this omitted intentionally?  It shows up under the installation/configuration section: https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-asset-config
