### ISSUE TITLE
[enterprise-4.8] Issue in file virt/virtual_machines/virtual_disks/virt-cloning-a-datavolume-using-smart-cloning.adoc

### ISSUE THREAD

**Issue by vagnerfarias** [openshift/openshift-docs#34917]
### Which section(s) is the issue in?
Cloning a data volume

### What needs fixing?
When the source PVC isn't in the default StorageClass, it's required to include "storageClassName: <name_of_storageclass>" in the yaml, as in the example below. If this isn't done, CDI will try to use the default StorageClass but it won't find the source PVC. It will also not generate any visible user error (user will have to check in cdi-deployment pod logs).

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cloner-datavolume
spec:
  source:
    pvc:
      namespace: "project-a" 
      name: "rhel8-test-vm"
  storage: 
    resources:
      requests:
        storage: 20Gi
    storageClassName: ocs-storagecluster-ceph-rbd
```
