### ISSUE TITLE
[enterprise-4.7] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by alexisph** [openshift/openshift-docs#35108]
### Which section(s) is the issue in?

Allowing traffic between projects when network isolation is enabled

### What needs fixing?

The NetworkPolicy listed in the documentation does not allow pods within the same namespace to communicate. As a result, the ES cluster is unable to initialize when first created. It needs to be modified as such:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-openshift-operators-redhat
  namespace: openshift-logging
spec:
  ingress:
    - from:
      - podSelector: {}
    - from:
      - namespaceSelector:
          matchLabels:
            project: openshift-operators-redhat
```
