### ISSUE TITLE
[enterprise-4.8] Issue in file networking/ingress-operator.adoc

### ISSUE THREAD

**Issue by AhyeongLee** [openshift/openshift-docs#35605]
### Which section(s) is the issue in?

Configuring an Ingress Controller to use an internal load balancer

https://docs.openshift.com/container-platform/4.8/networking/ingress-operator.html#nw-ingress-setting-internal-lb_configuring-ingress

### What needs fixing?
I created default ingresscontroller as internal nlb like below.

```yaml
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 2
  defaultCertificate:
    name: my-cluster-primary-cert-bundle-secret
  domain: my-cluster.yuoj.p1.openshiftapps.com
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
      providerParameters:
        type: AWS
        aws:
          type: NLB
    type: LoadBalancerService

```

But the nlb in aws, it was created in public subnet.
( nlb works very well. )

![image](https://user-images.githubusercontent.com/40782494/130040474-a1058694-1254-4929-9536-4f69b543785d.png)

How can I create internal nlb in a private subnet??
