### ISSUE TITLE
Jaeger log-level parameter doesn't accept trace

### ISSUE THREAD

**Issue by iblancasa** [openshift/openshift-docs#36099]
### Which section(s) is the issue in?
The possible values of the `log-level` parameter for Jaeger components.

### What needs fixing?
The `trace` verbosity level is not supported. The documentation lists the following verbosity levels: `trace`, `debug`, `info`, `warning`, `error`, `fatal` and `panic`.

#### How to reproduce

When this configuration is deployed:
```yaml
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: trace
```

The startup of the container fails  with this error:
```
Error: cannot create logger: unrecognized level: "trace"
```

The reason is Jaeger uses the [zap](https://github.com/uber-go/zap) logging library and it doesn't support `trace`.
