### ISSUE TITLE
[enterprise-4.8] Issue in file networking/configuring-ptp.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#36818]
### Which section(s) is the issue in?
Configuring Linuxptp services

### What needs fixing?
The guide says `node.Labels` and `node.Name` from the node object when specifying mutch rules in the PtpConfig CR object.

```
kind: PtpConfig
...
spec:
...
    match: 
    - nodeLabel: "node-role.kubernetes.io/worker" 
      nodeName: "dev-worker-0" 
```

* Specify nodeLabel with the key of node.Labels from the node object.
* Specify nodeName with node.Name from the node object.

I think these imply getting the key and the name using the `oc describe node` command, but it can be a bit confusing and not be friendly to tell us where they come from as long as we tell users to use the `oc describe` command.

```
[quicklab@upi-0 ~]$ oc describe node/worker-0.ocp4nh.lab.rdu2.cee.redhat.com | egrep '^Labels|Name'
Name:               worker-0.ocp4nh.lab.rdu2.cee.redhat.com
Labels:             beta.kubernetes.io/arch=amd64
```

Then, how about adding how to get the field?.

* Specify nodeLabel with the key of node.Labels from the node object using the oc describe node command.
* Specify nodeName with node.Name from the node object using the oc describe node command.
