### ISSUE TITLE
[enterprise-4.6] The provided examples in networking/network_policy/about-network-policy.adoc are wrong

### ISSUE THREAD

**Issue by MichaelWasher** [openshift/openshift-docs#37011]
The provided examples in the `networking/network_policy/about-network-policy.adoc` do not use the podSelector field correctly.

This results in an error of the following:
```
$ oc create -f ns.yaml --validate --dry-run=client
error: error validating "ns.yaml": error validating data: ValidationError(NetworkPolicy.spec.podSelector): unknown field "ingress" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false
```

### Which section(s) is the issue in?
The NetworkPolicy examples need to have `{}` after the `podSelector` field.
Below is an example from the page, however there are a couple of these and it appears to affect multiple versions of the OpenShift documentation.
From OpenShift 4.3+
https://docs.openshift.com/container-platform/4.8/networking/network_policy/about-network-policy.html

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
...
```

### What needs fixing?
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector: {}
  ingress:
  - from:
...
```
