### ISSUE TITLE
[enterprise-4.9] Incorrect Egress Firewall example for SDN

### ISSUE THREAD

**Issue by martinkennelly** [openshift/openshift-docs#38299]
### Which section(s) is the issue in?
Within network plugin SDN docs, https://docs.openshift.com/container-platform/4.9/networking/openshift_sdn/configuring-egress-firewall.html, there is an example of a firewall policy for network plugin OVN-kubernetes. It needs to be changed to a SDN example.

Example from the SDN doc:
```
apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
  name: default
  namespace: <namespace> 
spec:
  egress:
  - to:
      cidrSelector: <api_server_address_range> 
    type: Allow
# ...
  - to:
      cidrSelector: 0.0.0.0/0 
    type: Deny
```

### What needs fixing?
It needs to be changed to an SDN EgressNetworkPolicy example:
E.g.:
```
apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress:
.....
```
