### ISSUE TITLE
[enterprise-4.6] Issue in file post_installation_configuration/network-configuration.adoc

### ISSUE THREAD

**Issue by stefanvogel65** [openshift/openshift-docs#38586]
### Which section(s) is the issue in?

Section https://docs.openshift.com/container-platform/4.6/post_installation_configuration/network-configuration.html#nw-networkpolicy-project-defaults_post-install-network-configuration, the sample yaml in Procedure, step 2

### What needs fixing?

After this part:

```
objects:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-same-namespace
  spec:
    podSelector:
```

... two curly brackets need to be added after `podSelector:` so that it reads like this:

```
objects:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-same-namespace
  spec:
    podSelector: {}
```
