### ISSUE TITLE
[enterprise-4.9] Issue in file authentication/identity_providers/configuring-oidc-identity-provider.adoc

### ISSUE THREAD

**Issue by TiloGit** [openshift/openshift-docs#38974]
### Which section(s) is the issue in?

[Sample OpenID Connect CRs](https://docs.openshift.com/container-platform/4.9/authentication/identity_providers/configuring-oidc-identity-provider.html#identity-provider-oidc-CR_configuring-oidc-identity-provider)

`Standard OpenID Connect CR`
Item 5: 
_List of claims to use as the identity. First non-empty claim is used. At least one claim is required. If none of the listed claims have a value, authentication fails. For example, this uses the value of the sub claim in the returned id_token as the user’s identity._

But the sample YAML doesn't show sub in the claim list, nor it mapped to id_token. 

sample has
```yaml
      claims: 
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
```
### What needs fixing?
Fix example YAML or text of item. 

This goes back to OCP version 4.1 help docs it seems.
