### ISSUE TITLE
[enterprise-4.9] Issue in file logging/cluster-logging-enabling-json-logging.adoc

### ISSUE THREAD

**Issue by renatoppuccini** [openshift/openshift-docs#39533]
### Which section(s) is the issue in?
Json log formatter configuration examples are poor or missing whole information.

### What needs fixing?
It is best to have full examples of full object yamls instead of the information cut in pieces.

Today it has this in the docs:
```
pipelines:
- inputRefs: [ application ]
  outputRefs: myFluentd
  parse: json
```
or this:
```
outputDefaults:
- elasticsearch:
    structuredTypeKey: kubernetes.labels.logFormat 
    structuredTypeName: nologformat
pipelines:
- inputRefs: <application>
  outputRefs: default
  parse: json 
  ```

But it should be something like this. (This was is better so we avoid users that will need to infer or guess where they should go or what object or what part in the object they will need to edit):
```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  pipeline:
  - inputRefs: [ application ]
    outputRefs: [ elastic ]
  outputs:
  - name: elastic
  	type: elasticsearch
  	url: http://elasticsearch.openshift-logging.svc.cluster.local:9200
    elasticsearch:
      structuredTypeKey: kubernetes.label.appType
```
