### ISSUE TITLE
[enterprise-4.9] Issue in file authentication/ldap-syncing.adoc - 9. Define a config map that specifies the sync configuration file:

### ISSUE THREAD

**Issue by zeten30** [openshift/openshift-docs#39602]
### Which section(s) is the issue in?
[Automatically syncing LDAP groups](https://docs.openshift.com/container-platform/4.9/authentication/ldap-syncing.html#ldap-auto-syncing_ldap-syncing-groups)
- Define a config map that specifies the sync configuration file:

### What needs fixing?
Current version:
```
        spec:
          containers:
            - name: ldap-group-sync
              image: "openshift/origin-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - oc adm groups sync
                - --sync-config=/etc/config/ldap-group-sync.yaml --confirm 
```

Requested fix:
```
        spec:
          containers:
            - name: ldap-group-sync
              image: "openshift/origin-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync --sync-config=/etc/config/ldap-group-sync.yaml --confirm"
```

The whole 'oc ...' command must be passed as a single parameter/command to `bash -c <single param>`

```
# this is not executing the command above 
bash-5.1$ bash -c echo -e 'test\n'

# this is working properly
bash-5.1$ bash -c "echo -e 'test\n'"
test
```
