### ISSUE TITLE
[enterprise-4.6] Issue in file authentication/identity_providers/configuring-oidc-identity-provider.adoc

### ISSUE THREAD

**Issue by larsks** [openshift/openshift-docs#39899]
### Which section(s) is the issue in?

In the section "[Sample OpenID Connect CRs](https://docs.openshift.com/container-platform/4.6/authentication/identity_providers/configuring-oidc-identity-provider.html#identity-provider-oidc-CR_configuring-oidc-identity-provider)", there is the following example:

```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: oidcidp 
    mappingMethod: claim 
    type: OpenID
    openID:
      clientID: ... 
      clientSecret: 
        name: idp-secret
      claims: 
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      issuer: https://www.idp-issuer.com 
```

The text following includes this explanation of the `claims` value:

> List of claims to use as the identity. First non-empty claim is used. At least one claim is required. If none of the listed claims have a value, authentication fails. For example, this uses the value of the sub claim in the returned id_token as the user’s identity.

### What needs fixing?

The example does not make any use of the `sub` claim (and absent an additional example showing the claims provided by an IDP, there's no way to tell which of the claims listed in this example would be used to identity the user).
