### ISSUE TITLE
[enterprise-4.6] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by saumeya** [openshift/openshift-docs#39935]
### Which section(s) is the issue in?
Openshift docs -> under Networking -> under Configuring routes (https://docs.openshift.com/container-platform/4.8/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)

The Ingress Yaml that is written contains fields like `serviceName` and `servicePort` which are no longer supported and result in error

### What needs fixing?
Update the Yaml definition (there are 2 Yamls in the same section where this needs to be updated) to 
```
backend:        
  service:
    name: frontend
    port:
      number: 443
```
