### ISSUE TITLE
[enterprise-4.8] Issue in file authentication/ldap-syncing.adoc

### ISSUE THREAD

**Issue by cchen666** [openshift/openshift-docs#40367]
### Which section(s) is the issue in?

4.8 and 4.9

### What needs fixing?

* groupsQuery.filter is mandatory for rfc2307 LDAPSyncConfig while in the docs we have 
 
```
The attribute that uniquely identifies a group on the LDAP server. 
You cannot specify groupsQuery filters when using DN for groupUIDAttribute.
For fine-grained filtering, use the whitelist / blacklist method.
```

* Working yaml:

```
kind: LDAPSyncConfig
apiVersion: v1
url: ldap://<IP>:3268
bindDN: cn=rootadmin,CN=Users,DC=mylab,DC=local
bindPassword: <Password>
insecure: true
rfc2307:
    groupsQuery:
        baseDN: "OU=Groups,DC=bk,DC=mylab,DC=local"
        scope: sub
        derefAliases: never
        pageSize: 0
        filter: (|(cn=support)(cn=ocp-users))
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    groupMembershipAttributes: [ member ]
    usersQuery:
        baseDN: "OU=User-UAT,DC=uat,DC=mylab,DC=local"
        scope: sub
        derefAliases: never
        pageSize: 0
    userNameAttributes: [ sAMAccountName ]
    userUIDAttribute: dn
    tolerateMemberNotFoundErrors: true
    tolerateMemberOutOfScopeErrors: true
```

* Not working:

```
kind: LDAPSyncConfig
apiVersion: v1
url: ldap://<IP>:3268
bindDN: cn=rootadmin,CN=Users,DC=mylab,DC=local
bindPassword: <Password>
insecure: true
rfc2307:
    groupsQuery:
        baseDN: "OU=Groups,DC=bk,DC=mylab,DC=local"
        scope: sub
        derefAliases: never
        pageSize: 0
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    groupMembershipAttributes: [ member ]
    usersQuery:
        baseDN: "OU=User-UAT,DC=uat,DC=mylab,DC=local"
        scope: sub
        derefAliases: never
        pageSize: 0
    userNameAttributes: [ sAMAccountName ]
    userUIDAttribute: dn
    tolerateMemberNotFoundErrors: true
    tolerateMemberOutOfScopeErrors: true
```

* The errors indicate we need filter set

```
$ oc adm groups sync --sync-config=ldapsync.yaml --loglevel=6

F0110 14:33:07.221226   87485 helpers.go:116] error: validation of LDAP sync config failed: groupsQuery.filter: Invalid value: "": invalid query filter: LDAP Result Code 201 "Filter Compile Error": ldap: filter does not start with an '('
```
