### ISSUE TITLE
ConfigMap documentation is lacking an example with subPath

### ISSUE THREAD

**Issue by fgiloux** [openshift/openshift-docs#4108]
In the configMap [1] documentation there is no example for the use of subPath. This is a useful feature for images like the EAP S2I ones, where configuration files are located in a common directory. It is not that well known and it would be helpful to have an example in our documentation. Something like:

```
      volumeMounts:
      - name: jdbc-config-volume
        mountPath: /opt/eap/standalone/configuration/jdbc.properties
        subPath: jdbc.properties
  volumes:
    - name: jdbc-config-volume
      configMap:
        name: jdbc-config
```

[1] https://docs.openshift.com/container-platform/3.4/dev_guide/configmaps.html#configmaps-use-case-consuming-in-volumes
