### ISSUE TITLE
[enterprise-4.9] Issue in file virt/node_network/virt-updating-node-network-config.adoc

### ISSUE THREAD

**Issue by sirwalrus** [openshift/openshift-docs#42832]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/virt/node_network/virt-updating-node-network-config.html, specifically, the 
"Example: VLAN interface node network configuration policy"

Per https://bugzilla.redhat.com/show_bug.cgi?id=2017623#c13, the parent interface must also be specified when using a trunked VLAN on the host's primary interface. Without specifying the parent, the configuration will fail to apply. I just hit this problem, adding the base interface to the config fixed the issue.

### What needs fixing?

```
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-eth1-policy 
spec:
  nodeSelector: 
    kubernetes.io/hostname: <node01> 
  desiredState:
    interfaces:
    - name: eth1.102 
      description: VLAN using eth1 
      type: vlan 
      state: up 
      vlan:
        base-iface: eth1 
        id: 102 
```

Should be changed to:

```
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-eth1-policy 
spec:
  nodeSelector: 
    kubernetes.io/hostname: <node01> 
  desiredState:
    interfaces:
    - name: eth1
       description: parent interface
       state: up
       type: ethernet
    - name: eth1.102 
       description: VLAN using eth1 
       type: vlan 
       state: up 
       vlan:
         base-iface: eth1 
         id: 102 
```
