### ISSUE TITLE
[enterprise-Branch Build] Issue in file post_installation_configuration/storage-configuration.adoc

### ISSUE THREAD

**Issue by derekpoindexter** [openshift/openshift-docs#42963]
### Which section(s) is the issue in?

Supported dynamic provisioning plug-ins table.

### What needs fixing?

Add IBM Cloud Block Storage for VPC to the list.

| Storage type | Provisioner | Notes |
| --- | --- | --- |
| IBM Cloud Block Storage for VPC | vpc.block.csi.ibm.io | |

Example storage class

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <storage_class_name>
provisioner: vpc.block.csi.ibm.io
parameters:
  profile: "<profile>" # See https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-profiles for profiles
  csi.storage.k8s.io/fstype: "<file_system_type>" # Choose xfs, ext3, or ext4. The default value is ext4 and is used if you don't specify a file system.
  billingType: "hourly"
  encrypted: "(true|false)"
  encryptionKey: "<encryption_key>" # the root key CRN of your Key Protect service instance
  resourceGroup: "<resource_group>"
  zone: "<zone>" 
  region: "<region>"
  tags: "<tags>"
  generation: "gc"
  classVersion: "1"
  iops: "<iops>" # Only specify this parameter if you are using a "custom" profile.
allowVolumeExpansion: (true|false) # Select true or false. 
volumeBindingMode: <volume_binding_mode>
  # csi.storage.k8s.io/provisioner-secret-name: # Uncomment and add secret parameters to enforce encryption. 
  # csi.storage.k8s.io/provisioner-secret-namespace: 
reclaimPolicy: "<reclaim_policy>"

```
