### ISSUE TITLE
[enterprise-4.9] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by briantward** [openshift/openshift-docs#43227]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#configuring-the-monitoring-stack_configuring-the-monitoring-stack

### What needs fixing?

yaml for the prometheus volume needs to be corrected. Incorrect spacing starting at "spec"...

```
data:
  config.yaml: |
    prometheusK8s: 
      volumeClaimTemplate:
       spec:
         storageClassName: fast
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
```
