### ISSUE TITLE
[enterprise-4.10] Issue in file authentication/identity_providers/configuring-ldap-identity-provider.adoc

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-docs#43509]
### Which section(s) is the issue in?

TIP in

https://docs.openshift.com/container-platform/4.10/authentication/identity_providers/configuring-ldap-identity-provider.html#identity-provider-creating-configmap_configuring-ldap-identity-provider

### What needs fixing?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-config-map
  namespace: openshift-config
type: Opaque
data:
  ca.crt: |
    <CA_certificate_PEM>
```

Should not have the ```type``` line, config map doesn't have such. This fails.
