### ISSUE TITLE
master/node config documentation lists incorrect field names

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#4462]
All the field names in the tables on https://docs.openshift.com/container-platform/3.5/install_config/master_node_configuration.html#master-configuration-files use upper-case names, which do not correspond to the serialized names in the config files.

The json tag names in https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/types.go should be used for all field documentation

**Comment by soltysh** [comment]
Additionally, the current structure of tables does not reflect the actual structure of the file. One example of such error is in https://bugzilla.redhat.com/show_bug.cgi?id=1455479, where `maxImagesBulkImportedPerRepository` is mentioned in [Image Configuration](https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-image-config) but actually there are *two* structs inside `master-config.yaml` responsible for image config:
```yaml
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: true
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: registry.access.redhat.com
  - domainName: gcr.io
  - domainName: quay.io
  - domainName: '*.amazonaws.com'
  disableScheduledImport: false
  maxImagesBulkImportedPerRepository: 5
  maxScheduledImageImportsPerMinute: 60
  scheduledImageImportMinimumIntervalSeconds: 900
```

@ahardin-rh @adellape this is somehow related to #2866 as well, do you think we could have section by section including the samples for each? I think we could start with the default one generated at startup.
