### ISSUE TITLE
[enterprise-4.10] Issue in file _topic_maps/_topic_map.yml

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#44915]
### Which section(s) is the issue in?

```
Name: Installing
Dir: installing
Distros: openshift-origin,openshift-enterprise,openshift-webscale
```

### What needs fixing?

The following topic and subtopics are missing from 4.10 and 4.11:

```
- Name: Installing on oVirt
  Dir: installing_rhv
  Distros: openshift-origin
  Topics:
  - Name: Installing a cluster quickly on oVirt
    File: installing-rhv-default
  - Name: Installing a cluster on oVirt with customizations
    File: installing-rhv-customizations
  - Name: Installing a cluster on oVirt with user-provisioned infrastructure
    File: installing-rhv-user-infra
  - Name: Uninstalling a cluster on oVirt
    File: uninstalling-cluster-rhv
```

As a result, "Installing on oVirt" does not appear in [OKD docs](https://docs.okd.io/4.10/welcome/index.html) for 4.10 or 4.11.
