### ISSUE TITLE
[enterprise-4.10] Issue in file backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc

### ISSUE THREAD

**Issue by petercort** [openshift/openshift-docs#44980]
### Which section(s) is the issue in?

"Enabling CSI in the DataProtectionApplication CR"

Issue is in this section for all the 'Installing and Configuring OADP with XYZ' sections. 

### What needs fixing?
Current block is this: 
```
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - csi 
    featureFlags:
    - EnableCSI 
```

featureFlags node should be indented as it's part of spec/configuration/velero. 

Should be this: 
```
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - csi 
      featureFlags:
      - EnableCSI 
 ```
