### ISSUE TITLE
[enterprise-4.10] Issue in file virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc

### ISSUE THREAD

**Issue by krsacme** [openshift/openshift-docs#45011]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.html#virt-creating-single-pvc-template-storage-pool_virt-configuring-local-storage-for-vms

Step 2
```
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
 name: hostpath-provisioner
spec:
 imagePullPolicy: IfNotPresent
storagePools: 
   - name: <any_name>
     path: "</var/myvolumes>" 
       pvcTemplate:
       volumeMode: Block 
       storageClassName: <any_storage_class> 
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 5Gi 
   workload:
   nodeSelector:
     kubernetes.io/os: linux
```

### What needs fixing?
alignment of `storagePools` should be fixed, it throws error on mis alignment
