### ISSUE TITLE
[enterprise-4.9] Issue in file authentication/configuring-internal-oauth.adoc

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#46568]
### Which section(s) is the issue in?
Customizing the internal OAuth server URL

### What needs fixing?

I think this section is wrong 

apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: oauth-openshift
      namespace: openshift-authentication
      hostname: <custom_hostname> 
      servingCertKeyPairSecret:
        name: <secret_name> 

and should look like this instead

apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - hostname: <custom_hostname> 
      name: oauth-openshift
      namespace: openshift-authentication
      servingCertKeyPairSecret:
        name: <secret_name> 

Whats different is hostname and name. Look what you have in the document about customizing custom console URL

**Comment by bergerhoffer** [comment]
Hi @bortek, I'm comparing what we have in the section on customizing the internal OAuth server URL [1] to the section on customizing the console URL [2]. And they look similar to me

OAuth server:
```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: oauth-openshift
      namespace: openshift-authentication
      hostname: <custom_hostname> 
      servingCertKeyPairSecret:
        name: <secret_name> 
```
Console URL:
```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: console
      namespace: openshift-console
      hostname: <custom_hostname> 
      servingCertKeyPairSecret:
        name: <secret_name> 
```
I'm not seeing any examples that would list `hostname` first after `componentRoutes`. Can you please clarify what you're seeing?

[1] https://docs.openshift.com/container-platform/4.10/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth
[2] https://docs.openshift.com/container-platform/4.10/web_console/customizing-the-web-console.html#customizing-the-console-route_customizing-web-console

**Comment by bortek** [comment]
Sorry for confusion. To start with I was testing this on .49 not 4.10 but anyway the yamls in the links you sent were the same. 

What I was wondering about was that when I update these yamls as described in  [1] and steps 1 and 2 and then step 3 save and if I view the object after applying then it looks like this

oc edit ingress.config.openshift.io cluster

```
spec:
  appsDomain: mydomain.example.com
  componentRoutes:
  - hostname: oauth-openshift.mydomain.example.com
    name: oauth-openshift
    namespace: openshift-authentication
  - hostname: console.mydomain.example.com
    name: console
    namespace: openshift-console
  domain: apps.mydomain.example.com
```

which after changing lists the hostname with "-" prefix and name underneath without prefix. It was probably changed by the operator to look like this and my assumption was that possible it should be set like this to represent the desired state and avoid confusion. But perhaps this is only happening in my cluster.
