### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by beelzetron** [openshift/openshift-docs#46565]
### Which section(s) is the issue in?
Forwarding logs to external third-party logging systems

### What needs fixing?
Please include documentation on how to configure a forwarding only scenario without the internal logging stack configured.

**Comment by beelzetron** [comment]
To configure a forwarding only scenario the `ClusterLogging` instance has to be created like this:

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd: {}
      type: fluentd
  managementState: Managed
```
