### ISSUE TITLE
[enterprise-4.10] Issue in file networking/network_policy/multitenant-network-policy.adoc

### ISSUE THREAD

**Issue by fjcloud** [openshift/openshift-docs#46647]
### Which section(s) is the issue in?

Look like this Fix is not implemented in our docs so network policy for ingress is not working with router pods that are in hostNetwork mode.

[Network policy on OVN without ](https://github.com/openshift/okd/issues/526#issue-815252751)

### What needs fixing?

Fix docs related ingress parts. 

To get NetworkPolicies working you must set

```yaml
...
    - ports:
        - protocol: TCP
...

```
An example NetworkPolicy that works should look like this:

```yaml

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-ingress
spec:
  podSelector:
    matchLabels:
      pflaeging.net/networkrole: ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
    - ports:
        - protocol: TCP
  policyTypes:
    - Ingress

```
