### ISSUE TITLE
[enterprise-4.10] Issue in file security/seccomp-profiles.adoc

### ISSUE THREAD

**Issue by jgawor** [openshift/openshift-docs#46770]
### Which section(s) is the issue in?

doc: https://docs.openshift.com/container-platform/4.10/security/seccomp-profiles.html#configuring-default-seccomp-profile_configuring-seccomp-profiles
git: https://github.com/openshift/openshift-docs/blob/main/modules/configuring-default-seccomp-profile.adoc

### What needs fixing?

The following example is wrong:
```
spec:
  securityContext:
    seccompProfile:
    - runtime/default
      type: RuntimeDefault
```

it should be:
```
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
```
