### ISSUE TITLE
[online] Ignition spec in MachineConfig shall be updated to 3.2.0 after 4.7.+

### ISSUE THREAD

**Issue by borball** [openshift/openshift-docs#46827]
### Which section(s) is the issue in?

All the places.

### What needs fixing?

According to statement below in https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfiguration.md, 
It is better to update the Ignition spec to 3.2.0 for all the sample files in Openshift 4.7.+

The actual custom resource manifest then could look like this if you are applying it to cluster on version >= 4.7:

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: worker-2864988432
spec:
  config:
    ignition:
      version: 3.2.0
....
and like this if you are applying it to a cluster on version < 4.6:

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: worker-2864988432
spec:
  config:
    ignition:
      version: 2.2.0
....

```
