### ISSUE TITLE
policyConfig.openshiftInfrastructureNamespace addition to master config

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#474]
https://github.com/openshift/origin/pull/2777/files#diff-381e09db7a55a712234f2c2413f7d987 adds a configurable namespace used to hold infrastructure components. Currently, those consist of the service accounts used to run build controllers, replication controllers, and deployment controllers.

The option appears in the master config file under the policyConfig stanza:
```
policyConfig:
  bootstrapPolicyFile: ""
  openshiftInfrastructureNamespace: ""
  openshiftSharedResourcesNamespace: ""
...
```

If unspecified, the default value is "openshift-infra"

Currently, three privileged service accounts are created in the namespace on server start:
- `build-controller`, granted the `system:build-controller` role cluster-wide
- `deployment-controller`, granted the `system:deployment-controller` role cluster-wide
- `replication-controller`, granted the `system:replication-controller` role cluster-wide

These service accounts are used to run the corresponding controllers, and their usernames (e.g. `system:serviceaccount:openshift-infra:build-controller`) can be referenced in policy and/or security context constraints.
