### ISSUE TITLE
[enterprise-4.10] Issue in file cicd/gitops/configuring-sso-on-argo-cd-using-dex.adoc

### ISSUE THREAD

**Issue by dmoessne** [openshift/openshift-docs#47438]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/cicd/gitops/configuring-sso-on-argo-cd-using-dex.html#gitops-creating-a-new-client-in-dex_configuring-sso-for-argo-cd-using-dex

### What needs fixing?

We state that the following configuration should work:
```apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: openshift-oauth
spec:
  dex:
    openShiftOAuth: true 
    groups:
     - default
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'

```

and describe in the subsequent section how to add the group cluster-admins, However this did not work and i do get still a permission denied unless I add `cluster-admins` to the groups as well like so

```
spec:
  dex:
    openShiftOAuth: true 
    groups:
     - default
     - cluster-admins
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
```
So it looks the groups added in the policy section need to be also in the groups section above
