### ISSUE TITLE
[enterprise-4.8] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by gswallow** [openshift/openshift-docs#47810]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-router_creating-infrastructure-machinesets

### What needs fixing?

The advice to use NodeSelectors is bad.  Use tolerations instead.  See https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress, in particular the NodePlacement parameter.

The documentation on creating infrastructure nodes leads the reader to apply a taint to nodes with an infra role, but then pods in the openshift-ingress namespace can't be scheduled because the node selector doesn't override the taint, while a toleration matches, and allows the pods to run.  The way to patch the operator is:

```
cat > kustomization.yaml <<EOF
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - target:
      group: operator.openshift.io
      version: v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patch: |-
      - op: add
        path: /spec/nodePlacement
        value: {}
      - op: add
        path: /spec/nodePlacement/tolerations
        value: []
      - op: add
        path: /spec/nodePlacement/tolerations/0
        value: {}
      - op: replace
        path: /spec/nodePlacement/tolerations/0/effect
        value: NoSchedule
      - op: replace
        path: /spec/nodePlacement/tolerations/0/key
        value: node-role.kubernetes.io/infra
      - op: replace
        path: /spec/nodePlacement/tolerations/0/operator
        value: Exists

resources:
  - ingresscontroller.yaml
 EOF
oc get ingresscontroller default -oyaml -n openshift-ingress-operator > ingresscontroller.yaml
oc apply -k . 
```

In general, documentation like this -- with patches -- would be much more helpful to your readers.
