### ISSUE TITLE
[enterprise-4.10] Issue in file networking/network_policy/about-network-policy.adoc

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#48288]
### Which section(s) is the issue in?

About network policy

### What needs fixing?

It would be helpful to add sample network policies demonstrating egress filtering. For example:

To allow pods to to perform DNS queries via the cluster DNS service, add the following `NetworkPolicy` object:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - port: 5353
      protocol: TCP
    - port: 5353
      protocol: UDP
```
