### ISSUE TITLE
[enterprise-4.10] Issue in file backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc

### ISSUE THREAD

**Issue by AaronJaegerVA** [openshift/openshift-docs#48661]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.10/backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.html#oadp-about-backup-snapshot-locations_installing-oadp-ocs

### What needs fixing?
There is not enough information about how to use ODF's noobaa as object storage when defining a `BackupStorageLocation`. Please considering something like this:

## ODF Object Bucket Claim

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oadp-backup-bucket
  namespace: openshift-adp
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: oadp-backup-bucket-a3800b52-5019-47c9-9d2f-9cdcf9574c65
  generateBucketName: oadp-backup-bucket
  objectBucketName: obc-openshift-adp-oadp-backup-bucket
  storageClassName: openshift-storage.noobaa.io
```

## OADP - Velero DPA

```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-dpa
  namespace: openshift-adp
spec:
  backupImages: false
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
        - kubevirt
        - csi
      featureFlags:
        - EnableCSI
      noDefaultBackupLocation: true
```

## Backup Storage Location

```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: incluster-bsl
  namespace: openshift-adp
spec:
  config:
    profile: default
    region: noobaa
    s3ForcePathStyle: 'true'
    s3Url: 'https://s3.openshift-storage.svc'
    insecureSkipTLSVerify: "true"
  credential:
    key: cloud
    name: cloud-credentials
  objectStorage:
    bucket: oadp-backup-bucket-a3800b52-5019-47c9-9d2f-9cdcf9574c65
    prefix: valero
  default: true
  provider: aws
```
