### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/pods/nodes-pods-autoscaling-custom.adoc

### ISSUE THREAD

**Issue by mmayeras** [openshift/openshift-docs#49009]
### Which section(s) is the issue in?
Scaledjob definition
https://docs.openshift.com/container-platform/4.10/nodes/pods/nodes-pods-autoscaling-custom.html#nodes-pods-autoscaling-custom-creating-job_nodes-pods-autoscaling-custom

### What needs fixing?
The definition of the ScaledObject triggers is wrong :
  ```
 triggers:
  - type: prometheus 
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092/
      namespace: kedatest
      metricName: http_requests_total
      threshold: '5'
      query: sum(rate(http_requests_total{job="test-app"}[1m]))
      authModes: "bearer"
  - authenticationRef: 
      name: prom-triggerauthentication
    metadata:
      name: prom-triggerauthentication
     type: object
  - authenticationRef: 
      name: prom-cluster-triggerauthentication
    metadata:
      name: prom-cluster-triggerauthentication
    type: object
```
Should be :
```
triggers:
  - type: prometheus 
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092/
      namespace: kedatest
      metricName: http_requests_total
      threshold: '5'
      query: sum(rate(http_requests_total{job="test-app"}[1m]))
      authModes: "bearer"
      authenticationRef: 
        name: prom-triggerauthentication
```

**Comment by mburke5678** [comment]
@mmayeras Thank you for catching this. Not sure what happened here. 

One question, it appears [in the KEDA docs](https://keda.sh/docs/2.6/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication) that the  `authenticationRef` parameter is not part of the trigger metadata, but is at the same level as `type` and `metadata`. Can you confirm this? I will double check with the team here, too. 

```
# some Scaled Object
# ...
  triggers:
  - type: {scaler-type}
    metadata:
      param1: {some-value}
    authenticationRef:
      name: {trigger-authentication-name} # this may define other params not defined in metadata

```
