### ISSUE TITLE
[enterprise-4.11] Issue in file scalability_and_performance/cnf-numa-aware-scheduling.adoc

### ISSUE THREAD

**Issue by yangzhengtx** [openshift/openshift-docs#49692]
### Which section(s) is the issue in?
Deploying the NUMA-aware secondary pod scheduler
The example of KubeletConfig custom resource has incorrect indent for field limits in reservedMemory:
```yaml
    reservedMemory:
      - numaNode: 0
  limits:
    memory: "1124Mi"
```

### What needs fixing?
The correct format for reservedMemory should be:
```yaml
    reservedMemory:
      - numaNode: 0
      - limits:
          memory: "1124Mi"
```
