### ISSUE TITLE
[enterprise-4.11] Issue in file installing/installing_nutanix/installing-nutanix-installer-provisioned.adoc

### ISSUE THREAD

**Issue by waljaber** [openshift/openshift-docs#50018]
### Which section(s) is the issue in?
The issue is in the 'Sample customized install-config.yaml file for Nutanix' section
In the sample manifest on the doc page the username, and password are under the `nutanix` stanza.

### What needs fixing?
Accoring to the 4.11 installer binary the username, and password should be under the `prismCentral` stanza

```console
$ ./openshift-install explain installconfig.platform.nutanix.prismCentral
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <object>
  PrismCentral is the endpoint (address and port) and credentials to connect to the Prism Central.

FIELDS:
    endpoint <object> -required-
      Endpoint holds the address and port of the Prism Central

    password <string> -required-
      Password is the password for the user to connect to the Prism Central

    username <string> -required-
      Username is the name of the user to connect to the Prism Central
```

Therefor the correct manifest should look like this:

```yaml
apiVersion: v1
baseDomain: example.com 
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 3
  platform:
    nutanix: 
      cpus: 2
      coresPerSocket: 2
      memoryMiB: 8196
      osDisk:
        diskSizeGiB: 120
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3
  platform:
    nutanix: 
      cpus: 4
      coresPerSocket: 2
      memoryMiB: 16384
      osDisk:
        diskSizeGiB: 120
metadata:
  creationTimestamp: null
  name: test-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  nutanix:
    apiVIP: 10.40.142.7 
    ingressVIP: 10.40.142.8 
    prismCentral:
      endpoint:
        address: your.prismcentral.domainname 
        port: 9440 
      password: samplepassword   # Indented by 2 spaces to make bring it under 'prismCentral' stanza
      username: sampleadmin       # Indented by 2 spaces to make bring it under 'prismCentral' stanza
    prismElements:
    - endpoint:
        address: your.prismelement.domainname
        port: 9440
      uuid: 0005b0f1-8f43-a0f2-02b7-3cecef193712
    subnetUUIDs:
    - c7938dc6-7659-453e-a688-e26020c68e43
    clusterOSImage: http://example.com/images/rhcos-47.83.202103221318-0-nutanix.x86_64.ova 
credentialsMode: Manual
publish: External
pullSecret: '{"auths": ...}' 
fips: false 
sshKey: ssh-ed25519 AAAA...
```
