### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by alexissolanas** [openshift/openshift-docs#50443]
### Which section(s) is the issue in?

The YAML definition on point 4 of the Deploying the LokiStack section is incorrect:

```
  apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    name: cr-lokistack
    namespace: openshift-logging
  spec:
     logStore:
       lokistack:
         name: logging-loki
```

When trying to apply this, the following error is thrown:

```
oc apply -f clusterlogging.yaml
The ClusterLogging "cr-lokistack" is invalid:
* spec.logStore.type: Required value
* metadata.name: Unsupported value: "cr-lokistack": supported values: "instance"
```

### What needs fixing?

The correct YAML definition should be:

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  logStore:
    type: lokistack
    lokistack:
      name: lokistack-dev
```
