### ISSUE TITLE
[enterprise-4.11] Issue in file machine_management/creating_machinesets/creating-machineset-azure.adoc

### ISSUE THREAD

**Issue by KingOfSpades** [openshift/openshift-docs#51602]
### Which section(s) is the issue in?

Sample YAML for a machine set custom resource on Azure

### What needs fixing?

The example `yaml` for creating a new `MachineSet` on Azure proposes the following code:

```yaml
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
[...]
    spec:
      [...]
      providerSpec:
          image: 
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/<infrastructure_id>-rg/providers/Microsoft.Compute/images/<infrastructure_id> 
[...]
```

When creating a `resourceID` string with the placeholders, the Azure API returns a not found error. I also tried exploring the resource API in Azure, but could not find any API end-points matching the proposed URL. In the end, I went with copying the `providerSpec` from an existing machineset.
