### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by alanconway** [openshift/openshift-docs#51817]
### Which section(s) is the issue in?

Deploying lokistack

### What needs fixing?

Example ClusterLogging resource is incorrect, errors on apply:
```
The ClusterLogging "cr-lokistack" is invalid: 
* metadata.name: Unsupported value: "cr-lokistack": supported values: "instance"
* spec.logStore.type: Required value
```

Corrected version here:
```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
     type: lokistack
     lokistack:
       name: logging-loki
```
