### ISSUE TITLE
[enterprise-4.11] Issue in file networking/metallb/metallb-operator-install.adoc

### ISSUE THREAD

**Issue by robertodocampo** [openshift/openshift-docs#51826]
### Which section(s) is the issue in?

Hi the bug that i suposse is related to this section:

https://docs.openshift.com/container-platform/4.11/networking/metallb/metallb-operator-install.html
Section:  Limit speaker pods to specific nodes

### What needs fixing?

On the example the speakerToleration is not an array as described on the  api 

```yaml
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:  
    node-role.kubernetes.io/worker: ""
  speakerTolerations:   
    key: "Example"
    operator: "Exists"
    effect: "NoExecute"
```

 oc explain metallb.spec
```
  speakerTolerations   <[]Object>
     tolerations is a list of tolerations applied to metalLB controller
     deployments.
```

In fact if i try to apply the example the ocp returns this message:
```
The MetalLB "metallb" is invalid: spec.speakerTolerations: Invalid value: "object": spec.speakerTolerations in body must be of type array: "object"
````

I think that the example needs the "-" before the "key"  (i show in the below example)

```yaml
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:  
    node-role.kubernetes.io/worker: ""
  speakerTolerations:   
    - key: "Example"
      operator: "Exists"
      effect: "NoExecute"
```

Thanks so much!!
