### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by garethahealy** [openshift/openshift-docs#52476]
### Which section(s) is the issue in?
Enabling vector; example has an incorrect indentation. 

### What needs fixing?
docs show:

```
spec:
  collection:
  logs:
    type: "vector"
    vector: {}
```

should be:

```
spec:
  collection:
    type: "vector"
    vector: {}
```
