### ISSUE TITLE
[enterprise-4.11] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by martineg** [openshift/openshift-docs#53144]
### Which section(s) is the issue in?

Moving the router

### What needs fixing?

In the section _Moving the router_ the example spec for updating the ingresscontroller has a wrong intendation.

The example given lists
```
 spec:
    nodePlacement:
      nodeSelector: 
        matchLabels:
          node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved
```

while the `tolerations` field should be under the `nodePlacement` field as described by `oc explain ingresscontrollers.spec.nodePlacement`. The correct example should be

```
 spec:
    nodePlacement:
      nodeSelector: 
        matchLabels:
          node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
```
