### ISSUE TITLE
[enterprise-4.11] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by the-it-jaeger** [openshift/openshift-docs#53367]
### Which section(s) is the issue in?

[[Machine management](https://docs.openshift.com/container-platform/4.11/machine_management/index.html)  Creating infrastructure machine sets](https://docs.openshift.com/container-platform/4.11/machine_management/creating-infrastructure-machinesets.html#creating-infrastructure-machinesets-clouds)

### What needs fixing?

```YAML
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
    machine.openshift.io/cluster-api-machine-role: <infra>  # <--- I think this should be 'infra' without the '<>'
    machine.openshift.io/cluster-api-machine-type: <infra>  # <--- I think this should be 'infra' without the '<>'
  name: <infrastructure_id>-<infra>-<zone>  # <--- I think this should be 'infra' without the '<>' 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<infra>-<zone>  # <--- I think this should be 'infra' without the '<>' 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
        machine.openshift.io/cluster-api-machine-role: <infra>  # <--- I think this should be 'infra' without the '<>'
        machine.openshift.io/cluster-api-machine-type: <infra>  # <--- I think this should be 'infra' without the '<>'
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<infra>-<zone>  # <--- I think this should be 'infra' without the '<>' 
```
