### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-docs#53727]
### Which section(s) is the issue in?

The guide inconsistency led me waste a day. In middle of the guide the object names change a bit, and by following the guide I fail getting vektor forwarding to loki.

### What needs fixing?

Instructions create a lokistack named logging-loki:

```
  apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    name: instance
    namespace: openshift-logging
  spec:
    managementState: Managed
    logStore:
      type: lokistack
      lokistack:
        name: logging-loki
      collection:
        type: "vector"
```

instructions points to wrong name: lokistack-dev:

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  logStore:
    type: lokistack
    lokistack:
      name: lokistack-dev
  collection:
    type: vector
```

This latter name: lokistack-dev should be changed to match the above logging-loki. Otherwise the guide leads to broken env.
