### ISSUE TITLE
[enterprise-4.11] Issue in file cicd/pipelines/automatic-pruning-taskrun-pipelinerun.adoc

### ISSUE THREAD

**Issue by strangiato** [openshift/openshift-docs#53973]
### Which section(s) is the issue in?

References to any of the `operator.tekton.dev/prune.keep-since` annotations on the page.

### What needs fixing?

There are multiple references to the `operator.tekton.dev/prune.keep-since` that give examples of with the value as a number, such as the `Example of auto-pruning annotations` section.  The number however must be quoted to make it a string.

The following example results in the following error when attempting to apply the namespace:

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  annotations:
    operator.tekton.dev/prune.keep-since: 7200
    operator.tekton.dev/prune.resources: taskrun, pipelinerun
```

```
Namespace in version "v1" cannot be handled as a Namespace: json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string
```

The example should be corrected to this:

```
    operator.tekton.dev/prune.keep-since: "7200"
    operator.tekton.dev/prune.resources: taskrun, pipelinerun
```
