### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by KreshnikZ** [openshift/openshift-docs#53988]
### Which section(s) is the issue in?
The example yaml code with the title: "Sample Node object with a label"

### What needs fixing?
It is missing the label "type: user-node", because the next yaml code "Sample Pod object with node selectors" uses that nodeSelector.

**Comment by mburke5678** [comment]
@KreshnikZ  Thanks for your comment. I wonder if removing the `type: user-node` from the pod spec example might make more sense? Make it more simple?

```
apiVersion: v1
kind: Pod
....
spec:
  nodeSelector: 
    region: east
```
