### ISSUE TITLE
[enterprise-4.11] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by david-goudet** [openshift/openshift-docs#54058]
### Which section(s) is the issue in?

Installing the ImageContentSourcePolicy and CatalogSource resources into the cluster

### What needs fixing?

Describe how to use the content of generated ImageContentSourcePolicy in install-config.yaml for fully disconnected OCP cluster installation. 
As describe in section "Installing the ImageContentSourcePolicy and CatalogSource resources into the cluster" for existant cluster, Add section:

"Installing fully disconnected cluster with the ImageContentSourcePolicy and CatalogSource resources" 

To enable installation of cluster from disconnected registry, add content of oc-mirror-workspace/results-<date>/imageContentSourcePolicy.yaml in install-config.yaml.

Also replace step 2 of https://docs.openshift.com/container-platform/4.11/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-modify-install-config-for-a-disconnected-registry_ipi-install-installation-workflow by referencing this new section. The step 2 in documentation does not work with oc-mirror:

imageContentSourcePolicy.yaml generated by oc-mirror:
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay-server.example.com/gui/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - quay-server.example.com/gui/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```

imageContentSourcePolicy.yaml generated by oc adm ... in step 2 of documentation:
```
imageContentSources:
- mirrors:
  - registry.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
- mirrors:
  - registry.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```
