### ISSUE TITLE
[enterprise-4.11] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by david-goudet** [openshift/openshift-docs#54060]
### Which section(s) is the issue in?

"Modify the install-config.yaml file to use the disconnected registry"

### What needs fixing?

Step 2 is not working with oc-mirror, see below the difference:

imageContentSourcePolicy.yaml generated by oc-mirror:
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay-server.example.com/gui/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - quay-server.example.com/gui/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```

imageContentSourcePolicy.yaml generated by oc adm ... in step 2 of documentation:
```
imageContentSources:
- mirrors:
  - registry.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
- mirrors:
  - registry.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```

Replace step 2  by referencing new section asked in https://github.com/openshift/openshift-docs/issues/54058.
Documentation https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected should be referenced to use imageContentSourcePolicy.yaml file generated by oc-mirror.
