### ISSUE TITLE
[enterprise-4.11] Issue in file nodes/pods/nodes-pods-priority.adoc

### ISSUE THREAD

**Issue by ehvs** [openshift/openshift-docs#54104]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/nodes/pods/nodes-pods-priority.html
Section: Pod priority classes
Paragraph: system-cluster-critical 

### What needs fixing?

It mentions that Fluentd (collector) pods runs with PriorityClass : system-cluster-critical.
But when checking the Collector pod in a default installation, it can be seen that runs with `cluster-logging` Priorityclass

```
  priorityClassName: cluster-logging
status:
  phase: Running
  conditions:
```
My suggestion is to remove `Fluentd` from the list of `system-cluster-critical`

**Comment by mburke5678** [comment]
@ehvs Thank you for your comment. 

I took a look at a 4.13 cluster that was available. I installed Red Hat OpenShift Logging v 5.5.5.  I see the following in each of the `collector-*` pods in the `openshift-logging` namespace. Any thoughts?

```
kind: Pod
apiVersion: v1
metadata:
  generateName: collector-
...
  priorityClassName: system-node-critical
```

I am trying to get a 4.11 cluster to take a look there.

**Comment by mburke5678** [comment]
@ehvs I see the same in a 4.11 cluster (4.11.0-0.nightly-2023-01-17-083429):

```
kind: Pod
apiVersion: v1
metadata:
  generateName: collector-
...
  priorityClassName: system-node-critical
```

I am going to close this issue. Please re-open if I am mistaken.
