### ISSUE TITLE
[enterprise-4.11] Issue in file backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc

### ISSUE THREAD

**Issue by muellerfabi** [openshift/openshift-docs#54575]
### Which section(s) is the issue in?
"Enabling CSI in the DataProtectionApplication CR" section
Also the other pages "Installing and configuring OADP with ***" are affected.

### What needs fixing?
The featureFlags field is placed wrong in documentation. `spec.configuration.featureFlags` does not exist.
Correct is:
```
spec:
  configuration:
    velero:
      featureFlags:
      - EnableCSI 
```
