### ISSUE TITLE
extra-manifest folder name should not be used for extraManifestPath field value as it clashes with the existing ones

### ISSUE THREAD

**Issue by ccardenosa** [openshift/openshift-docs#55374]
Having this file hierarchy:
```
$ tree site-configs/
site-configs/
|-- extra-manifest
|   `-- 10_update_os_baseimage.yaml
|-- kustomization.yaml
`-- sno-cnfdf23.yaml
```
And this configuration in the SiteConfig manifest file:
```
. . .
  clusters:
  - clusterName: "cnfdf23"
    biosConfigRef:
      filePath: "hardware-profiles/vDU-HW.profile"
    extraManifestPath: extra-manifest
 . . .
```
GitOps fails upon running `kustomize build` for this SiteConfig setup due to the name is already in used:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build .site-configs --enable-alpha-plugins` failed exit status 1: 2023/01/31 08:53:13 Error could not create extra-manifest cnfdf23.extra-manifest Pre-defined extra-manifest cannot be over written 10_update_os_baseimage.yaml 2023/01/31 08:53:13 Error: could not build the entire SiteConfig defined by /tmp/kust-plugin-config-2736365460: Pre-defined extra-manifest cannot be over written 10_update_os_baseimage.yaml Error: failure in plugin configured via /tmp/kust-plugin-config-2736365460; exit status 1: exit status 1
```

It can be reproduced here:

```
$ kustomize build site-configs/ --enable-alpha-plugins
[1868/1868]
2023/01/31 05:40:52 Error could not create extra-manifest
cnfdf23.extra-manifest Pre-defined extra-manifest cannot be over written
01-example-machine-config.yaml
2023/01/31 05:40:52 Error: could not build the entire SiteConfig defined
by /tmp/kust-plugin-config-1090227213: Pre-defined extra-manifest cannot
be over written 01-example-machine-config.yaml
Error: failure in plugin configured via
/tmp/kust-plugin-config-1090227213; exit status 1: exit status 1
```
As show below, it can be found in the default hierarchy:
```
$ find /root/.config/kustomize/ -type f -name *machine*yaml
/root/.config/kustomize/plugin/ran.openshift.io/v1/policygentemplate/source-crs/extra-manifest/03-sctp-machine-config-master.yaml
/root/.config/kustomize/plugin/ran.openshift.io/v1/policygentemplate/source-crs/extra-manifest/03-sctp-machine-config-worker.yaml
/root/.config/kustomize/plugin/ran.openshift.io/v1/siteconfig/extra-manifest/03-sctp-machine-config-master.yaml
/root/.config/kustomize/plugin/ran.openshift.io/v1/siteconfig/extra-manifest/03-sctp-machine-config-worker.yaml
```

### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/main/modules/ztp-customizing-the-install-extra-manifests.adoc

### What needs fixing?
The problem can be sorted out just by changing `extra-manifest` value for something else like `custom-manifest`:

Fail:
```
clusters:
- clusterName: "example-sno"
  networkType: "OVNKubernetes"
  extraManifestPath: extra-manifest
```

Ok:
```
clusters:
- clusterName: "example-sno"
  networkType: "OVNKubernetes"
  extraManifestPath: custom-manifest
```
