### ISSUE TITLE
[enterprise-4.12] Sample YAML issues in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by evanstoner** [openshift/openshift-docs#55404]
### Which section(s) is the issue in?

"Deploying the LokiStack" and "Enabling Vector" 

### What needs fixing?

1. Indention in `spec.collection` section is incorrect, and there is excess indention.

```yaml
# excess 2 spaces on left, aggravating for copy and paste
  apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    name: instance
    namespace: openshift-logging
  spec:
    managementState: Managed
    logStore:
      type: lokistack
      lokistack:
        name: logging-loki
      collection: # over indented, should align with logStore
        type: "vector" # over indented because parent is over indented
```

2. Excess indention

```yaml
# excess 2 spaces on left, aggravating for copy and paste
  apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    name: instance
    namespace: openshift-logging
  spec:
    managementState: Managed
    logStore:
      type: lokistack
      lokistack:
        name: logging-loki
      collection:
        type: "vector"
```

3. Sample in "Enabling Vector" contains several issues.

```yaml
# excess 2 spaces on left, aggravating for copy and paste
  apiVersion: "logging.openshift.io/v1"
  kind: "ClusterLogging"
  metadata:
    name: "instance"
    namespace: "openshift-logging"
    annotations:
      logging.openshift.io/preview-vector-collector: enabled # this references a preview but Vector is GA?
  spec:
    collection:
    logs: # this appears to be an error, collection.logs is deprecated according to UI hints
      type: "vector" # type should be nested under collection, not logs
      vector: {} # collection.vector is not explained in the docs and not shown in the Create ClusterLogging form view
```
