### ISSUE TITLE
[enterprise-4.10] Issue in file service_mesh/v2x/servicemesh-release-notes.adoc - supported versions are: [v2.0 v2.1 v2.2 v2.3]

### ISSUE THREAD

**Issue by k-wall** [openshift/openshift-docs#55442]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.12/service_mesh/v2x/ossm-create-smcp.html#ossm-control-plane-deploy-cli_ossm-create-smcp

### What needs fixing?

I am using

```
oc version
Client Version: v4.2.0-alpha.0-1570-g3c85519
Kustomize Version: v4.5.4
Server Version: 4.12.0
Kubernetes Version: v1.25.4+77bec7a
```

am I trying to apply:

```
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.3.1
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
```

with command:

```
oc apply -f  /tmp/istio-installation.yaml
```

but it fails like this:

```
Error from server: error when creating "/tmp/istio-installation.yaml": admission webhook "smcp.validation.maistra.io" denied the request: invalid Version specified; supported versions are: [v2.0 v2.1 v2.2 v2.3]
```
