### ISSUE TITLE
Remove Support section from OKD docs

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#58576]
Please remove the "Support" section of the OKD Product Docs.

https://github.com/okd-project/working-group/issues/2

**Comment by mburke5678** [comment]
PR in progress: https://github.com/openshift/openshift-docs/pull/58577

**Comment by gabriel-rh** [comment]
Based on the topic map, should the "Getting support" page be output at all for OKD?

```
Name: Support
Dir: support
Distros: openshift-enterprise,openshift-online,openshift-origin
Topics:
- Name: Support overview
  File: index
- Name: Managing your cluster resources
  File: managing-cluster-resources
- Name: Getting support
  File: getting-support
  Distros: openshift-enterprise
```

I would have thought that the Distros: setting on the File: would override that on the Dir: and as a result, asciibinder should not output this page for OKD but it does...
