### ISSUE TITLE
Should not have `kubernetesMasterConfig` in cluster resource override example

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#7105]
The overcommitment topic should not have the CRO config under `kubernetesMasterConfig`. It should be under a top-level `admissionConfig` property.

https://docs.openshift.org/latest/admin_guide/overcommit.html#configuring-masters-for-overcommitment

```
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
      ClusterResourceOverride:   
        configuration:
          apiVersion: v1
          kind: ClusterResourceOverrideConfig
          memoryRequestToLimitPercent: 25  
          cpuRequestToLimitPercent: 25     
          limitCPUToMemoryPercent: 200 
```

should instead be

```
admissionConfig:
  pluginConfig:
    ClusterResourceOverride:   
      configuration:
        apiVersion: v1
        kind: ClusterResourceOverrideConfig
        memoryRequestToLimitPercent: 25  
        cpuRequestToLimitPercent: 25     
        limitCPUToMemoryPercent: 200 
```

cc @deads2k @jwforres @ahardin-rh
