### ISSUE TITLE
Redeploying Router Certs

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-docs#7553]
@knobunc is this still valid? https://docs.openshift.com/container-platform/3.7/install_config/redeploying_certificates.html#redeploying-router-certificates-manually (and latest)?

I just did a fresh ansible install and it looks like the service is not actually annotated to get a service signing cert and instead uses a secret volume that is mounted into the defaultCertificatePath.

```
# oc get service router -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1936"
    prometheus.io/scrape: "true"
    prometheus.openshift.io/password: 3TEDNiXgSm
    prometheus.openshift.io/username: admin
  creationTimestamp: 2018-02-03T14:59:04Z

# oc get dc/router -o yaml | grep -A2 secret
          value: /etc/secret-volume/router.pem
        - name: ROUTER_EXTERNAL_HOST_USERNAME
        - name: ROUTER_EXTERNAL_HOST_VXLAN_GW_CIDR
--
        secret:
          defaultMode: 420
          secretName: router-certs
  test: false
  triggers:

# oc get secrets | grep router
router-certs               kubernetes.io/tls                     2         2h
router-dockercfg-76bs6     kubernetes.io/dockercfg               1         2h
router-token-dx9nt         kubernetes.io/service-account-token   4         2h
router-token-lkxmg         kubernetes.io/service-account-token   4         2h

```
