### ISSUE TITLE
Working with the privileged SCC

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#775]
The docs at https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc need a little enhancement. Ref. https://github.com/openshift/origin/issues/3762

It needs to mention:
1. That pod specs can include their required securityContext, and what that looks like (example, link to docs, etc.)
2. That SCCs are evaluated to find the most restrictive that can be applied according to the pod's specified needs. So if the pod doesn't declare what it needs, it could be matched up and run under an incompatible SCC. Preferably we would have examples of what happens when the user makes a mistake; one for when the user tries to create a pod requiring privileges it can't have, and one for when the pod doesn't declare the privileges it actually needs (RunAsUser).
3. That the SCC the pod is running under is annotated on the pod e.g.
       `openshift.io/scc: restricted`
4. Example of adding a service account user to the privileged SCC since that is the most likely path for targeted additions.

@pweil-

**Comment by sosiouxme** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
spec:
  containers:
    securityContext:
      privileged: false
      runAsUser: 0
```

**Comment by tanen01** [comment]
Why doesn't this work for pods deployed by replicationControllers?

**Comment by danni** [comment]
@tanen01 make sure you're putting it in the second metadata, for the pod spec.

**Comment by bmcelvee** [comment]
Hey @sosiouxme! Since this issue was opened a couple of versions back, does this enhancement still need to be added to the documentation?

**Comment by php-coder** [comment]
> does this enhancement still need to be added to the documentation?

I feel that yes, it still needed.

**Comment by bmcelvee** [comment]
Thanks, @php-coder!

**Comment by sosiouxme** [comment]
It's still needed, though SCCs might be deprecated by the time this happens...

**Comment by shanemcd** [comment]
I'm having trouble getting this to work with a `Deployment`. Here's what I'm trying:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        openshift.io/scc: privileged
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
          - containerPort: 80
        securityContext:
          privileged: false
          runAsUser: 0
```

With this I'm seeing:

```
Error creating: pods "nginx-deployment-1986025071-" is forbidden: unable to validate against any security context constraint: [securityContext.runAsUser: Invalid value: 0: UID on container nginx does not match required range. Found 0, required min: 1000020000 max: 1000029999]
```

I've also tried adding the annotation to the top-level `metadata` with no luck.
