### ISSUE TITLE
routing docs do not document context 

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#779]
The route object can take a context (eg: foo.com/context/stuff). This is not currently in the docs.

https://docs.openshift.com/enterprise/3.0/dev_guide/routes.html

**Comment by mburke5678** [comment]
@thoraxe Can you provide some more info on this? 

Do you mean that the spec::host parameter can take a path? 
host: www.example.com/directory/file

**Comment by thoraxe** [comment]
Yeah. Path is now in the picture of the UI:

https://docs.openshift.com/container-platform/3.5/dev_guide/routes.html

But it's still not called out in the YAML example:

```yaml
apiVersion: v1
kind: Route
metadata:
  name: frontend
spec:
  host: www.example.com
  to:
    kind: Service
    name: frontend
```

It might be nice to add more definitions and components to the docs here.
