### ISSUE TITLE
cluster_metrics is missing routes configuration

### ISSUE THREAD

**Issue by goern** [openshift/openshift-docs#801]
I have been reading through https://docs.openshift.org/latest/admin_guide/cluster_metrics.html# and it seems to me that the document is missing the configuration for routes to access grafana. Adding a route manually results in missing data from influx.
The route I added:

```
apiVersion: v1
kind: Route
metadata:
  name: route-grafana
spec:
  host: grafana.<DOMAINNAME>
  to:
    kind: Service
    name: grafana
```
