### ISSUE TITLE
[enterprise-4.16] observability/logging/modules/logging-loki-cli-install.adoc

### ISSUE THREAD

**Issue by pfeifferj** [openshift/openshift-docs#82528]
### Which section(s) is the issue in?
`observability/logging/modules/logging-loki-cli-install.adoc`

### What needs fixing?

step 13. in this section https://docs.openshift.com/container-platform/4.16/observability/logging/cluster-logging-deploying.html#logging-loki-cli-install_cluster-logging-deploying

uses the following example:

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  collection:
    type: vector
  logStore:
    lokistack:
      name: logging-loki
    retentionPolicy:
      application:
        maxAge: 7d
      audit:
        maxAge: 7d
      infra:
        maxAge: 7d
    type: lokistack
  visualization:
    ocpConsole:
      logsLimit: 15
  managementState: Managed
```

the example config is missing a required `ClusterLogging.spec.visualization.type` value:

```
❯ oc explain ClusterLogging.spec.visualization
GROUP:      logging.openshift.io
KIND:       ClusterLogging
VERSION:    v1

FIELD: visualization <Object>

DESCRIPTION:
    Specification of the Visualization component for the cluster

FIELDS:
  kibana        <Object>
    Specification of the Kibana Visualization component

  nodeSelector  <map[string]string>
    Define which Nodes the Pods are scheduled on.

  ocpConsole    <Object>
    OCPConsole is the specification for the OCP console plugin

  tolerations   <[]Object>
    Define the tolerations the Pods will accept

  type  <string> -required-
    The type of Visualization to configure
```

the same applies to 11e in the GUI section https://docs.openshift.com/container-platform/4.16/observability/logging/cluster-logging-deploying.html#logging-loki-gui-install_cluster-logging-deploying
