### ISSUE TITLE
[enterprise-3.9] Edit suggested in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by falencastro** [openshift/openshift-docs#8828]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html#pod-autoscaling-memory

Place the following in a file, such as hpa.yaml:

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-memory 
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1 
    kind: ReplicationController 
    name: hello-hpa-memory 
  minReplicas: 1 
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50 
```

### What needs fixing?

The sample api versions on hpa.yml don't work on 3.9.

I had to replace apiVersion and scaleTargetRef->apiVersion to be like this:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-memory 
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: ReplicationController 
    name: hello-hpa-memory 
  minReplicas: 1 
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50 
```
