### ISSUE TITLE
[rfe] need nodeport docs

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#884]
perhaps something like:

2) non-TLS traffic
For software that cannot speak over TLS or HTTP, you can use the
"NodePort" directive in a service. It's only loosely documented:

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html#services

Here's the correct syntax:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: NodePort
  selector:
    docker-registry: default
  portalIP: 172.30.136.123
  ports:
  - protocol: TCP
    targetPort: 5000
```

When doing this, you will get assigned a high port (>32k) that will be
mapped externally on all nodes. This would include the nodes where the
router is running. So if you already have a DNS entry pointing to some
IP address where a router is, you could do:

somedomain.com:32xxx

This would then use the kubernetes service layer to direct your traffic
to endpoints.

not sure if this is fully tested/works yet. May also be better suited in the "routing" section in contrast to things that can use TLS/SNI...
