### ISSUE TITLE
Document extension configuration options

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#935]
See https://github.com/openshift/origin/pull/3699

Example master configuration:

``` yaml
assetConfig:
  extensionScripts:
   - "/home/vagrant/extensions/extension1/js/ext1.js"
   - "/home/vagrant/extensions/extension2/js/ext2.js"
  extensionStylesheets:
   - "/home/vagrant/extensions/extension1/css/ext1.css"
   - "/home/vagrant/extensions/extension2/css/ext2.css"
  extensions:
   - name: "ext1"
     sourceDirectory: "/home/vagrant/extensions/extension1/files/"
     html5Mode: true
   - name: "ext2"
     sourceDirectory: "/home/vagrant/extensions/extension2/files/"
```

**extensionScripts** are Javascript files loaded at console startup.
**extensionStylesheets** are CSS files included at console startup.
**extensions** are files available under the `/console/extensions/<name>/` subcontext.
**html5Mode** will redirect to index.html when a file is not found rather than giving a 404 not found error. It also tells OpenShift to inject the correct base value for the extension context into index.html. This is useful if you're writing AngularJS apps.

All paths are to files on the asset server (relative to the master-config.yaml if relative paths are used).

Optional assetConfig parameter **extensionDevelopment** (boolean) tells the server to always reload  extension scripts and stylesheets on each request. This lets you write extensions without restarting the server for every change and is only recommended for development.
